/* oxlint-disable */
// This file is auto-generated by scripts/generate-rules.ts
// Do not edit this file directly.

export {
  BUILTIN_PLUGIN_NAMES,
  BUILTIN_RULE_NAMES,
  RULES_BY_PLUGIN,
} from '../plugins/index.generated'

export type {
  BuiltinPluginName,
  BuiltinRuleName,
  BuiltinRuleOptionsByName,
  RulesByPlugin,
} from '../plugins/index.generated'
