import fs from 'node:fs'
import path from 'node:path'
import { toPascalCase, toUpperSnakeCase } from './case-utils'
import {
  COMPAT_RULES_OUTPUT_PATH,
  PLUGINS_DIR,
  PLUGINS_INDEX_OUTPUT_PATH,
} from './constants'
import type { ParsedRules } from './types'

/**
 * Formats an exported readonly string tuple constant.
 * @param name Constant name to emit.
 * @param values Tuple values to include.
 * @returns TypeScript source for one exported readonly tuple constant.
 */
export function toTsArray(name: string, values: string[]): string {
  const body = values.map(value => `  ${JSON.stringify(value)},`).join('\n')
  return `export const ${name} = [\n${body}\n] as const\n`
}

/**
 * Builds one plugin-level generated TypeScript output file content.
 * @param pluginName Public plugin id.
 * @param pluginRules Sorted rule names for the plugin.
 * @param optionsByRuleName Map of namespaced rule name to option type.
 * @returns Complete TypeScript file content for one plugin.
 */
export function buildPluginGeneratedFileContent(
  pluginName: string,
  pluginRules: string[],
  optionsByRuleName: Record<string, string>,
): string {
  const pascal = toPascalCase(pluginName)
  const constPrefix = toUpperSnakeCase(pluginName)
  const constName = `${constPrefix}_RULE_NAMES`
  const ruleNameTypeName = `${pascal}RuleName`
  const optionsTypeName = `${pascal}RuleOptionsByName`

  const namespacedRules = pluginRules.map(
    ruleName => `${pluginName}/${ruleName}`,
  )
  const optionsBody = namespacedRules
    .map(ruleName => {
      const optionType = optionsByRuleName[ruleName] ?? 'unknown'
      return `  ${JSON.stringify(ruleName)}: ${optionType}`
    })
    .join('\n')

  return `/* oxlint-disable */
// This file is auto-generated by scripts/generate-rules.ts
// Do not edit this file directly.

${toTsArray(constName, pluginRules)}
export type ${ruleNameTypeName} = typeof ${constName}[number]

export interface ${optionsTypeName} {
${optionsBody}
}
`
}

/**
 * Builds the aggregate plugin index file content.
 * @param parsed Parsed normalized rule metadata.
 * @param optionsByRuleName Map of namespaced rule name to option type.
 * @returns Complete TypeScript index content for all generated plugins.
 */
export function buildPluginsIndexFileContent(
  parsed: ParsedRules,
  optionsByRuleName: Record<string, string>,
): string {
  const imports = parsed.pluginNames
    .map(pluginName => {
      const pascal = toPascalCase(pluginName)
      const constName = `${toUpperSnakeCase(pluginName)}_RULE_NAMES`
      const optionsTypeName = `${pascal}RuleOptionsByName`
      const ruleNameTypeName = `${pascal}RuleName`
      return `import { ${constName} } from './${pluginName}.generated'
import type { ${optionsTypeName}, ${ruleNameTypeName} } from './${pluginName}.generated'`
    })
    .join('\n')

  const pluginNamesConst = toTsArray('BUILTIN_PLUGIN_NAMES', parsed.pluginNames)
  const ruleNamesConst = toTsArray('BUILTIN_RULE_NAMES', parsed.sortedRuleNames)

  const rulesByPluginBody = parsed.pluginNames
    .map(pluginName => {
      const constName = `${toUpperSnakeCase(pluginName)}_RULE_NAMES`
      return `  ${JSON.stringify(pluginName)}: ${constName},`
    })
    .join('\n')

  const optionsExtends = parsed.pluginNames
    .map(pluginName => `${toPascalCase(pluginName)}RuleOptionsByName`)
    .join(', ')

  const aliasLines = parsed.canonicalRules
    .flatMap(rule => {
      const namespaced = rule.namespacedRuleName
      return rule.ruleNames
        .filter(ruleName => ruleName !== namespaced)
        .toSorted()
        .map(alias => {
          const optionType = optionsByRuleName[namespaced] ?? 'unknown'
          return `  ${JSON.stringify(alias)}: ${optionType}`
        })
    })
    .join('\n')

  const ruleUnion = parsed.pluginNames
    .map(pluginName => `${toPascalCase(pluginName)}RuleName`)
    .join(' | ')

  return `/* oxlint-disable */
// This file is auto-generated by scripts/generate-rules.ts
// Do not edit this file directly.

${imports}

${pluginNamesConst}
${ruleNamesConst}
export const RULES_BY_PLUGIN = {
${rulesByPluginBody}
} as const

export interface BuiltinRuleOptionsByName extends ${optionsExtends} {
${aliasLines}
}

export type BuiltinPluginName = typeof BUILTIN_PLUGIN_NAMES[number]
export type BuiltinRuleName = typeof BUILTIN_RULE_NAMES[number]
export type RulesByPlugin = typeof RULES_BY_PLUGIN
export type BuiltinNamespacedRuleName = ${ruleUnion}
`
}

/**
 * Builds compatibility re-exports under `src/rules/generated.ts`.
 * @returns TypeScript source for the compatibility re-export module.
 */
export function buildRulesCompatFileContent(): string {
  return `/* oxlint-disable */
// This file is auto-generated by scripts/generate-rules.ts
// Do not edit this file directly.

export {
  BUILTIN_PLUGIN_NAMES,
  BUILTIN_RULE_NAMES,
  RULES_BY_PLUGIN,
} from '../plugins/index.generated'

export type {
  BuiltinPluginName,
  BuiltinRuleName,
  BuiltinRuleOptionsByName,
  RulesByPlugin,
} from '../plugins/index.generated'
`
}

/**
 * Writes all generated plugin and index files to disk.
 * @param parsed Parsed normalized rule metadata.
 * @param optionsByRuleName Map of namespaced rule name to option type.
 * @returns Nothing.
 */
export function writePluginFiles(
  parsed: ParsedRules,
  optionsByRuleName: Record<string, string>,
): void {
  fs.mkdirSync(PLUGINS_DIR, { recursive: true })
  const existingGeneratedFiles = fs
    .readdirSync(PLUGINS_DIR, { withFileTypes: true })
    .filter(
      entry =>
        entry.isFile() &&
        entry.name.endsWith('.generated.ts') &&
        entry.name !== 'index.generated.ts',
    )

  for (const entry of existingGeneratedFiles) {
    fs.rmSync(path.join(PLUGINS_DIR, entry.name), { force: true })
  }

  for (const pluginName of parsed.pluginNames) {
    const pluginRules = parsed.sortedRulesByPlugin[pluginName] ?? []
    const pluginFilePath = path.join(PLUGINS_DIR, `${pluginName}.generated.ts`)
    const content = buildPluginGeneratedFileContent(
      pluginName,
      pluginRules,
      optionsByRuleName,
    )
    fs.writeFileSync(pluginFilePath, content, 'utf8')
  }

  fs.writeFileSync(
    PLUGINS_INDEX_OUTPUT_PATH,
    buildPluginsIndexFileContent(parsed, optionsByRuleName),
    'utf8',
  )
  fs.writeFileSync(
    COMPAT_RULES_OUTPUT_PATH,
    buildRulesCompatFileContent(),
    'utf8',
  )
}
