/* oxlint-disable */
// This file is auto-generated by scripts/generate-rules.ts
// Do not edit this file directly.

export const ESLINT_RULE_NAMES = [
  'accessor-pairs',
  'array-callback-return',
  'arrow-body-style',
  'block-scoped-var',
  'capitalized-comments',
  'class-methods-use-this',
  'complexity',
  'constructor-super',
  'curly',
  'default-case',
  'default-case-last',
  'default-param-last',
  'eqeqeq',
  'for-direction',
  'func-name-matching',
  'func-names',
  'func-style',
  'getter-return',
  'grouped-accessor-pairs',
  'guard-for-in',
  'id-length',
  'init-declarations',
  'logical-assignment-operators',
  'max-classes-per-file',
  'max-depth',
  'max-lines',
  'max-lines-per-function',
  'max-nested-callbacks',
  'max-params',
  'max-statements',
  'new-cap',
  'no-alert',
  'no-array-constructor',
  'no-async-promise-executor',
  'no-await-in-loop',
  'no-bitwise',
  'no-caller',
  'no-case-declarations',
  'no-class-assign',
  'no-compare-neg-zero',
  'no-cond-assign',
  'no-console',
  'no-const-assign',
  'no-constant-binary-expression',
  'no-constant-condition',
  'no-constructor-return',
  'no-continue',
  'no-control-regex',
  'no-debugger',
  'no-delete-var',
  'no-div-regex',
  'no-dupe-class-members',
  'no-dupe-else-if',
  'no-dupe-keys',
  'no-duplicate-case',
  'no-duplicate-imports',
  'no-else-return',
  'no-empty',
  'no-empty-character-class',
  'no-empty-function',
  'no-empty-pattern',
  'no-empty-static-block',
  'no-eq-null',
  'no-eval',
  'no-ex-assign',
  'no-extend-native',
  'no-extra-bind',
  'no-extra-boolean-cast',
  'no-extra-label',
  'no-fallthrough',
  'no-func-assign',
  'no-global-assign',
  'no-implicit-coercion',
  'no-implicit-globals',
  'no-import-assign',
  'no-inline-comments',
  'no-inner-declarations',
  'no-invalid-regexp',
  'no-irregular-whitespace',
  'no-iterator',
  'no-label-var',
  'no-labels',
  'no-lone-blocks',
  'no-lonely-if',
  'no-loop-func',
  'no-loss-of-precision',
  'no-magic-numbers',
  'no-misleading-character-class',
  'no-multi-assign',
  'no-multi-str',
  'no-negated-condition',
  'no-nested-ternary',
  'no-new',
  'no-new-func',
  'no-new-native-nonconstructor',
  'no-new-wrappers',
  'no-nonoctal-decimal-escape',
  'no-obj-calls',
  'no-object-constructor',
  'no-param-reassign',
  'no-plusplus',
  'no-promise-executor-return',
  'no-proto',
  'no-prototype-builtins',
  'no-redeclare',
  'no-regex-spaces',
  'no-restricted-exports',
  'no-restricted-globals',
  'no-restricted-imports',
  'no-restricted-properties',
  'no-return-assign',
  'no-script-url',
  'no-self-assign',
  'no-self-compare',
  'no-sequences',
  'no-setter-return',
  'no-shadow',
  'no-shadow-restricted-names',
  'no-sparse-arrays',
  'no-template-curly-in-string',
  'no-ternary',
  'no-this-before-super',
  'no-throw-literal',
  'no-unassigned-vars',
  'no-undef',
  'no-undefined',
  'no-underscore-dangle',
  'no-unexpected-multiline',
  'no-unmodified-loop-condition',
  'no-unneeded-ternary',
  'no-unreachable',
  'no-unsafe-finally',
  'no-unsafe-negation',
  'no-unsafe-optional-chaining',
  'no-unused-expressions',
  'no-unused-labels',
  'no-unused-private-class-members',
  'no-unused-vars',
  'no-use-before-define',
  'no-useless-assignment',
  'no-useless-backreference',
  'no-useless-call',
  'no-useless-catch',
  'no-useless-computed-key',
  'no-useless-concat',
  'no-useless-constructor',
  'no-useless-escape',
  'no-useless-rename',
  'no-useless-return',
  'no-var',
  'no-void',
  'no-warning-comments',
  'no-with',
  'object-shorthand',
  'operator-assignment',
  'prefer-arrow-callback',
  'prefer-const',
  'prefer-destructuring',
  'prefer-exponentiation-operator',
  'prefer-numeric-literals',
  'prefer-object-has-own',
  'prefer-object-spread',
  'prefer-promise-reject-errors',
  'prefer-regex-literals',
  'prefer-rest-params',
  'prefer-spread',
  'prefer-template',
  'preserve-caught-error',
  'radix',
  'require-await',
  'require-unicode-regexp',
  'require-yield',
  'sort-imports',
  'sort-keys',
  'sort-vars',
  'symbol-description',
  'unicode-bom',
  'use-isnan',
  'valid-typeof',
  'vars-on-top',
  'yoda',
] as const

export type EslintRuleName = (typeof ESLINT_RULE_NAMES)[number]

export interface EslintRuleOptionsByName {
  'eslint/accessor-pairs': {
    setWithoutGet?: boolean
    getWithoutSet?: boolean
    enforceForClassMembers?: boolean
    enforceForTSTypes?: boolean
  }
  'eslint/array-callback-return': {
    checkForEach?: boolean
    allowImplicit?: boolean
    allowVoid?: boolean
  }
  'eslint/arrow-body-style': readonly [
    'as-needed' | 'always' | 'never',
    {
      requireReturnForObjectLiteral?: boolean
    },
  ]
  'eslint/block-scoped-var': never
  'eslint/capitalized-comments': readonly [
    'Always' | 'Never',
    {
      base?: {
        ignorePattern?: string
        ignoreInlineComments?: boolean
        ignoreConsecutiveComments?: boolean
      }
      line?: {
        ignorePattern?: string
        ignoreInlineComments?: boolean
        ignoreConsecutiveComments?: boolean
      }
      block?: {
        ignorePattern?: string
        ignoreInlineComments?: boolean
        ignoreConsecutiveComments?: boolean
      }
    },
  ]
  'eslint/class-methods-use-this': {
    exceptMethods?: readonly {
      name?: string
      private?: boolean
    }[]
    enforceForClassFields?: boolean
    ignoreOverrideMethods?: boolean
    ignoreClassesWithImplements?: 'all' | 'public-fields'
  }
  'eslint/complexity': {
    max?: number
    variant?: 'classic' | 'modified'
  }
  'eslint/constructor-super': never
  'eslint/curly': readonly [
    'all' | 'multi' | 'multi-line' | 'multi-or-nest',
    'consistent',
  ]
  'eslint/default-case': {
    commentPattern?: string
  }
  'eslint/default-case-last': never
  'eslint/default-param-last': never
  'eslint/eqeqeq': readonly [
    'always' | 'smart',
    {
      null?: 'always' | 'never' | 'ignore'
    },
  ]
  'eslint/for-direction': never
  'eslint/func-name-matching': readonly [
    'always' | 'never',
    {
      considerPropertyDescriptor?: boolean
      includeCommonJSModuleExports?: boolean
    },
  ]
  'eslint/func-names': readonly [
    'always' | 'as-needed' | 'never',
    {
      generators?: 'always' | 'as-needed' | 'never'
    },
  ]
  'eslint/func-style': readonly [
    'expression' | 'declaration',
    {
      allowArrowFunctions?: boolean
      allowTypeAnnotation?: boolean
      overrides?: {
        namedExports?: 'ignore' | 'expression' | 'declaration'
      }
    },
  ]
  'eslint/getter-return': {
    allowImplicit?: boolean
  }
  'eslint/grouped-accessor-pairs': readonly [
    'anyOrder' | 'getBeforeSet' | 'setBeforeGet',
    {
      enforceForTSTypes?: boolean
    },
  ]
  'eslint/guard-for-in': never
  'eslint/id-length': {
    exceptionPatterns?: readonly string[]
    exceptions?: readonly string[]
    max?: number
    min?: number
    checkGeneric?: boolean
    properties?: 'Always' | 'Never'
  }
  'eslint/init-declarations': readonly [
    'always' | 'never',
    {
      ignoreForLoopInit?: boolean
    },
  ]
  'eslint/logical-assignment-operators': readonly [
    'always' | 'never',
    {
      enforceForIfStatements?: boolean
    },
  ]
  'eslint/max-classes-per-file': {
    max?: number
    ignoreExpressions?: boolean
  }
  'eslint/max-depth': {
    max?: number
  }
  'eslint/max-lines': {
    max?: number
    skipBlankLines?: boolean
    skipComments?: boolean
  }
  'eslint/max-lines-per-function': {
    max?: number
    skipComments?: boolean
    skipBlankLines?: boolean
    IIFEs?: boolean
  }
  'eslint/max-nested-callbacks': {
    max?: number
  }
  'eslint/max-params': {
    max?: number
    countThis?: 'always' | 'never' | 'except-void'
    countVoidThis?: boolean
  }
  'eslint/max-statements': {
    max?: number
    ignoreTopLevelFunctions?: boolean
  }
  'eslint/new-cap': {
    newIsCap?: boolean
    capIsNew?: boolean
    newIsCapExceptions?: readonly string[]
    newIsCapExceptionPattern?: string
    capIsNewExceptions?: readonly string[]
    capIsNewExceptionPattern?: string
    properties?: boolean
  }
  'eslint/no-alert': never
  'eslint/no-array-constructor': never
  'eslint/no-async-promise-executor': never
  'eslint/no-await-in-loop': never
  'eslint/no-bitwise': {
    allow?: readonly string[]
    int32Hint?: boolean
  }
  'eslint/no-caller': never
  'eslint/no-case-declarations': never
  'eslint/no-class-assign': never
  'eslint/no-compare-neg-zero': never
  'eslint/no-cond-assign': 'except-parens' | 'always'
  'eslint/no-console': {
    allow?: readonly string[]
  }
  'eslint/no-const-assign': never
  'eslint/no-constant-binary-expression': never
  'eslint/no-constant-condition': {
    checkLoops?: 'all' | 'allExceptWhileTrue' | 'none'
  }
  'eslint/no-constructor-return': never
  'eslint/no-continue': never
  'eslint/no-control-regex': never
  'eslint/no-debugger': never
  'eslint/no-delete-var': never
  'eslint/no-div-regex': never
  'eslint/no-dupe-class-members': never
  'eslint/no-dupe-else-if': never
  'eslint/no-dupe-keys': never
  'eslint/no-duplicate-case': never
  'eslint/no-duplicate-imports': {
    includeExports?: boolean
    allowSeparateTypeImports?: boolean
  }
  'eslint/no-else-return': {
    allowElseIf?: boolean
  }
  'eslint/no-empty': {
    allowEmptyCatch?: boolean
  }
  'eslint/no-empty-character-class': never
  'eslint/no-empty-function': {
    allow?: readonly (
      | 'functions'
      | 'arrowFunctions'
      | 'generatorFunctions'
      | 'methods'
      | 'generatorMethods'
      | 'getters'
      | 'setters'
      | 'constructors'
      | 'asyncFunctions'
      | 'asyncMethods'
      | 'privateConstructors'
      | 'protectedConstructors'
      | 'decoratedFunctions'
      | 'overrideMethods'
    )[]
  }
  'eslint/no-empty-pattern': {
    allowObjectPatternsAsParameters?: boolean
  }
  'eslint/no-empty-static-block': never
  'eslint/no-eq-null': never
  'eslint/no-eval': {
    allowIndirect?: boolean
  }
  'eslint/no-ex-assign': never
  'eslint/no-extend-native': {
    exceptions?: readonly string[]
  }
  'eslint/no-extra-bind': never
  'eslint/no-extra-boolean-cast': {
    enforceForInnerExpressions?: boolean
  }
  'eslint/no-extra-label': never
  'eslint/no-fallthrough': {
    commentPattern?: string
    allowEmptyCase?: boolean
    reportUnusedFallthroughComment?: boolean
  }
  'eslint/no-func-assign': never
  'eslint/no-global-assign': {
    exceptions?: readonly string[]
  }
  'eslint/no-implicit-coercion': {
    boolean?: boolean
    number?: boolean
    string?: boolean
    disallowTemplateShorthand?: boolean
    allow?: never
  }
  'eslint/no-implicit-globals': unknown
  'eslint/no-import-assign': never
  'eslint/no-inline-comments': {
    ignorePattern?: string
  }
  'eslint/no-inner-declarations': readonly [
    'Functions' | 'Both',
    {
      blockScopedFunctions?: 'Allow' | 'Disallow'
    },
  ]
  'eslint/no-invalid-regexp': {
    allowConstructorFlags?: readonly unknown[]
  }
  'eslint/no-irregular-whitespace': {
    skipStrings?: boolean
    skipComments?: boolean
    skipRegExps?: boolean
    skipTemplates?: boolean
    skipJSXText?: boolean
  }
  'eslint/no-iterator': never
  'eslint/no-label-var': never
  'eslint/no-labels': {
    allowLoop?: boolean
    allowSwitch?: boolean
  }
  'eslint/no-lone-blocks': never
  'eslint/no-lonely-if': never
  'eslint/no-loop-func': never
  'eslint/no-loss-of-precision': never
  'eslint/no-magic-numbers': {
    ignore?: readonly unknown[]
    ignoreArrayIndexes?: boolean
    ignoreDefaultValues?: boolean
    ignoreClassFieldInitialValues?: boolean
    enforceConst?: boolean
    detectObjects?: boolean
    ignoreEnums?: boolean
    ignoreNumericLiteralTypes?: boolean
    ignoreReadonlyClassProperties?: boolean
    ignoreTypeIndexes?: boolean
  }
  'eslint/no-misleading-character-class': {
    allowEscape?: boolean
  }
  'eslint/no-multi-assign': {
    ignoreNonDeclaration?: boolean
  }
  'eslint/no-multi-str': never
  'eslint/no-negated-condition': never
  'eslint/no-nested-ternary': never
  'eslint/no-new': never
  'eslint/no-new-func': never
  'eslint/no-new-native-nonconstructor': never
  'eslint/no-new-wrappers': never
  'eslint/no-nonoctal-decimal-escape': never
  'eslint/no-obj-calls': never
  'eslint/no-object-constructor': never
  'eslint/no-param-reassign': {
    props?: boolean
    ignorePropertyModificationsFor?: unknown
    ignorePropertyModificationsForRegex?: readonly string[]
  }
  'eslint/no-plusplus': {
    allowForLoopAfterthoughts?: boolean
  }
  'eslint/no-promise-executor-return': {
    allowVoid?: boolean
  }
  'eslint/no-proto': never
  'eslint/no-prototype-builtins': never
  'eslint/no-redeclare': {
    builtinGlobals?: boolean
  }
  'eslint/no-regex-spaces': never
  'eslint/no-restricted-exports': {
    restrictedNamedExports?: unknown
    restrictedNamedExportsPattern?: string
    restrictDefaultExports?: {
      defaultFrom?: boolean
      direct?: boolean
      named?: boolean
      namedFrom?: boolean
      namespaceFrom?: boolean
    }
    hasDefaultRestrictedNamedExport?: boolean
  }
  'eslint/no-restricted-globals': {
    restrictedGlobals?: unknown
  }
  'eslint/no-restricted-imports': unknown
  'eslint/no-restricted-properties': readonly {
    object?: string
    property?: string
    message?: string
    allowObjects?: readonly string[]
    allowProperties?: readonly string[]
  }[]
  'eslint/no-return-assign': 'always' | 'except-parens'
  'eslint/no-script-url': never
  'eslint/no-self-assign': {
    props?: boolean
  }
  'eslint/no-self-compare': never
  'eslint/no-sequences': {
    allowInParentheses?: boolean
  }
  'eslint/no-setter-return': never
  'eslint/no-shadow': {
    hoist?: 'all' | 'functions' | 'functions-and-types' | 'never' | 'types'
    allow?: readonly string[]
    ignoreTypeValueShadow?: boolean
    ignoreFunctionTypeParameterNameValueShadow?: boolean
    builtinGlobals?: boolean
    ignoreOnInitialization?: boolean
  }
  'eslint/no-shadow-restricted-names': {
    reportGlobalThis?: boolean
  }
  'eslint/no-sparse-arrays': never
  'eslint/no-template-curly-in-string': never
  'eslint/no-ternary': never
  'eslint/no-this-before-super': never
  'eslint/no-throw-literal': never
  'eslint/no-unassigned-vars': never
  'eslint/no-undef': {
    typeof?: boolean
  }
  'eslint/no-undefined': never
  'eslint/no-underscore-dangle': {
    allowAfterSuper?: boolean
    allowAfterThisConstructor?: boolean
    allow?: readonly string[]
    allowAfterThis?: boolean
    allowInArrayDestructuring?: boolean
    allowInObjectDestructuring?: boolean
    allowFunctionParams?: boolean
    enforceInClassFields?: boolean
    enforceInMethodNames?: boolean
  }
  'eslint/no-unexpected-multiline': never
  'eslint/no-unmodified-loop-condition': never
  'eslint/no-unneeded-ternary': {
    defaultAssignment?: boolean
  }
  'eslint/no-unreachable': never
  'eslint/no-unsafe-finally': never
  'eslint/no-unsafe-negation': {
    enforceForOrderingRelations?: boolean
  }
  'eslint/no-unsafe-optional-chaining': {
    disallowArithmeticOperators?: boolean
  }
  'eslint/no-unused-expressions': {
    allowShortCircuit?: boolean
    allowTernary?: boolean
    allowTaggedTemplates?: boolean
    enforceForJSX?: boolean
  }
  'eslint/no-unused-labels': never
  'eslint/no-unused-private-class-members': never
  'eslint/no-unused-vars': {
    vars?: 'all' | 'local'
    varsIgnorePattern?: 'Default' | 'None'
    args?: 'after-used' | 'all' | 'none'
    argsIgnorePattern?: 'Default' | 'None'
    ignoreRestSiblings?: boolean
    caughtErrors?: boolean
    caughtErrorsIgnorePattern?: 'Default' | 'None'
    destructuredArrayIgnorePattern?: 'Default' | 'None'
    ignoreClassWithStaticInitBlock?: boolean
    ignoreUsingDeclarations?: boolean
    reportUsedIgnorePattern?: boolean
    reportVarsOnlyUsedAsTypes?: boolean
    fix?: {
      imports?: 'off' | 'suggestion' | 'fix' | 'safe-fix'
      variables?: 'off' | 'suggestion' | 'fix' | 'safe-fix'
    }
  }
  'eslint/no-use-before-define': {
    allowNamedExports?: boolean
    classes?: boolean
    enums?: boolean
    functions?: boolean
    ignoreTypeReferences?: boolean
    typedefs?: boolean
    variables?: boolean
  }
  'eslint/no-useless-assignment': never
  'eslint/no-useless-backreference': never
  'eslint/no-useless-call': never
  'eslint/no-useless-catch': never
  'eslint/no-useless-computed-key': {
    enforceForClassMembers?: boolean
  }
  'eslint/no-useless-concat': never
  'eslint/no-useless-constructor': never
  'eslint/no-useless-escape': {
    allowRegexCharacters?: readonly unknown[]
  }
  'eslint/no-useless-rename': {
    ignoreDestructuring?: boolean
    ignoreImport?: boolean
    ignoreExport?: boolean
  }
  'eslint/no-useless-return': never
  'eslint/no-var': never
  'eslint/no-void': {
    allowAsStatement?: boolean
  }
  'eslint/no-warning-comments': unknown
  'eslint/no-with': never
  'eslint/object-shorthand': readonly [
    (
      | 'always'
      | 'methods'
      | 'properties'
      | 'consistent'
      | 'consistent-as-needed'
      | 'never'
    ),
    {
      avoidQuotes?: boolean
      ignoreConstructors?: boolean
      avoidExplicitReturnArrows?: boolean
      methodsIgnorePattern?: string
    },
  ]
  'eslint/operator-assignment': 'always' | 'never'
  'eslint/prefer-arrow-callback': unknown
  'eslint/prefer-const': {
    destructuring?: 'any' | 'all'
    ignoreReadBeforeAssign?: boolean
  }
  'eslint/prefer-destructuring': {
    VariableDeclarator?: {
      array?: boolean
      object?: boolean
    }
    AssignmentExpression?: {
      array?: boolean
      object?: boolean
    }
    enforceForRenamedProperties?: boolean
  }
  'eslint/prefer-exponentiation-operator': never
  'eslint/prefer-numeric-literals': never
  'eslint/prefer-object-has-own': never
  'eslint/prefer-object-spread': never
  'eslint/prefer-promise-reject-errors': {
    allowEmptyReject?: boolean
  }
  'eslint/prefer-regex-literals': unknown
  'eslint/prefer-rest-params': never
  'eslint/prefer-spread': never
  'eslint/prefer-template': never
  'eslint/preserve-caught-error': {
    requireCatchParameter?: boolean
  }
  'eslint/radix': 'always' | 'as-needed'
  'eslint/require-await': never
  'eslint/require-unicode-regexp': {
    requireFlag?: 'u' | 'v'
  }
  'eslint/require-yield': never
  'eslint/sort-imports': {
    ignoreCase?: boolean
    ignoreDeclarationSort?: boolean
    ignoreMemberSort?: boolean
    allowSeparatedGroups?: boolean
    memberSyntaxSortOrder?: readonly ('None' | 'All' | 'Multiple' | 'Single')[]
  }
  'eslint/sort-keys': readonly [
    'Desc' | 'Asc',
    {
      caseSensitive?: boolean
      natural?: boolean
      minKeys?: number
      allowLineSeparatedGroups?: boolean
    },
  ]
  'eslint/sort-vars': {
    ignoreCase?: boolean
  }
  'eslint/symbol-description': never
  'eslint/unicode-bom': 'always' | 'never'
  'eslint/use-isnan': {
    enforceForSwitchCase?: boolean
    enforceForIndexOf?: boolean
  }
  'eslint/valid-typeof': {
    requireStringLiterals?: boolean
  }
  'eslint/vars-on-top': never
  'eslint/yoda': readonly [
    'never' | 'always',
    {
      exceptRange?: boolean
      onlyEquality?: boolean
    },
  ]
}
