/* oxlint-disable */
// This file is auto-generated by scripts/generate-rules.ts
// Do not edit this file directly.

export const IMPORT_RULE_NAMES = [
  'consistent-type-specifier-style',
  'default',
  'export',
  'exports-last',
  'extensions',
  'first',
  'group-exports',
  'max-dependencies',
  'named',
  'namespace',
  'newline-after-import',
  'no-absolute-path',
  'no-amd',
  'no-anonymous-default-export',
  'no-commonjs',
  'no-cycle',
  'no-default-export',
  'no-duplicates',
  'no-dynamic-require',
  'no-empty-named-blocks',
  'no-mutable-exports',
  'no-named-as-default',
  'no-named-as-default-member',
  'no-named-default',
  'no-named-export',
  'no-namespace',
  'no-nodejs-modules',
  'no-relative-parent-imports',
  'no-self-import',
  'no-unassigned-import',
  'no-webpack-loader-syntax',
  'prefer-default-export',
  'unambiguous',
] as const

export type ImportRuleName = (typeof IMPORT_RULE_NAMES)[number]

export interface ImportRuleOptionsByName {
  'import/consistent-type-specifier-style': 'prefer-top-level' | 'prefer-inline'
  'import/default': never
  'import/export': never
  'import/exports-last': never
  'import/extensions': {
    ignorePackages?: boolean
    requireExtension?: unknown
    checkTypeImports?: boolean
    extensions?: unknown
    pathGroupOverrides?: readonly {
      pattern?: string
      action?: 'Enforce' | 'Ignore'
    }[]
  }
  'import/first': 'absolute-first' | 'disable-absolute-first'
  'import/group-exports': never
  'import/max-dependencies': {
    max?: number
    ignoreTypeImports?: boolean
  }
  'import/named': never
  'import/namespace': {
    allowComputed?: boolean
  }
  'import/newline-after-import': unknown
  'import/no-absolute-path': {
    esmodule?: boolean
    commonjs?: boolean
    amd?: boolean
  }
  'import/no-amd': never
  'import/no-anonymous-default-export': {
    allowArray?: boolean
    allowArrowFunction?: boolean
    allowAnonymousClass?: boolean
    allowAnonymousFunction?: boolean
    allowCallExpression?: boolean
    allowNew?: boolean
    allowLiteral?: boolean
    allowObject?: boolean
  }
  'import/no-commonjs': {
    allowPrimitiveModules?: boolean
    allowRequire?: boolean
    allowConditionalRequire?: boolean
  }
  'import/no-cycle': {
    maxDepth?: number
    ignoreTypes?: boolean
    ignoreExternal?: boolean
    allowUnsafeDynamicCyclicDependency?: boolean
  }
  'import/no-default-export': never
  'import/no-duplicates': {
    preferInline?: boolean
    considerQueryString?: boolean
  }
  'import/no-dynamic-require': {
    esmodule?: boolean
  }
  'import/no-empty-named-blocks': never
  'import/no-mutable-exports': never
  'import/no-named-as-default': never
  'import/no-named-as-default-member': never
  'import/no-named-default': never
  'import/no-named-export': never
  'import/no-namespace': {
    ignore?: readonly string[]
  }
  'import/no-nodejs-modules': {
    allow?: unknown
  }
  'import/no-relative-parent-imports': never
  'import/no-self-import': never
  'import/no-unassigned-import': {
    allow?: readonly string[]
  }
  'import/no-webpack-loader-syntax': never
  'import/prefer-default-export': {
    target?: 'single' | 'any'
  }
  'import/unambiguous': never
}
