/* oxlint-disable */
// This file is auto-generated by scripts/generate-rules.ts
// Do not edit this file directly.

import { ESLINT_RULE_NAMES } from './eslint.generated'
import type {
  EslintRuleOptionsByName,
  EslintRuleName,
} from './eslint.generated'
import { IMPORT_RULE_NAMES } from './import.generated'
import type {
  ImportRuleOptionsByName,
  ImportRuleName,
} from './import.generated'
import { JEST_RULE_NAMES } from './jest.generated'
import type { JestRuleOptionsByName, JestRuleName } from './jest.generated'
import { JSDOC_RULE_NAMES } from './jsdoc.generated'
import type { JsdocRuleOptionsByName, JsdocRuleName } from './jsdoc.generated'
import { JSX_A11Y_RULE_NAMES } from './jsx-a11y.generated'
import type {
  JsxA11yRuleOptionsByName,
  JsxA11yRuleName,
} from './jsx-a11y.generated'
import { NEXTJS_RULE_NAMES } from './nextjs.generated'
import type {
  NextjsRuleOptionsByName,
  NextjsRuleName,
} from './nextjs.generated'
import { NODE_RULE_NAMES } from './node.generated'
import type { NodeRuleOptionsByName, NodeRuleName } from './node.generated'
import { OXC_RULE_NAMES } from './oxc.generated'
import type { OxcRuleOptionsByName, OxcRuleName } from './oxc.generated'
import { PROMISE_RULE_NAMES } from './promise.generated'
import type {
  PromiseRuleOptionsByName,
  PromiseRuleName,
} from './promise.generated'
import { REACT_PERF_RULE_NAMES } from './react-perf.generated'
import type {
  ReactPerfRuleOptionsByName,
  ReactPerfRuleName,
} from './react-perf.generated'
import { REACT_RULE_NAMES } from './react.generated'
import type { ReactRuleOptionsByName, ReactRuleName } from './react.generated'
import { TYPESCRIPT_RULE_NAMES } from './typescript.generated'
import type {
  TypescriptRuleOptionsByName,
  TypescriptRuleName,
} from './typescript.generated'
import { UNICORN_RULE_NAMES } from './unicorn.generated'
import type {
  UnicornRuleOptionsByName,
  UnicornRuleName,
} from './unicorn.generated'
import { VITEST_RULE_NAMES } from './vitest.generated'
import type {
  VitestRuleOptionsByName,
  VitestRuleName,
} from './vitest.generated'
import { VUE_RULE_NAMES } from './vue.generated'
import type { VueRuleOptionsByName, VueRuleName } from './vue.generated'

export const BUILTIN_PLUGIN_NAMES = [
  'eslint',
  'import',
  'jest',
  'jsdoc',
  'jsx-a11y',
  'nextjs',
  'node',
  'oxc',
  'promise',
  'react',
  'react-perf',
  'typescript',
  'unicorn',
  'vitest',
  'vue',
] as const

export const BUILTIN_RULE_NAMES = [
  '@typescript-eslint/adjacent-overload-signatures',
  '@typescript-eslint/array-type',
  '@typescript-eslint/await-thenable',
  '@typescript-eslint/ban-ts-comment',
  '@typescript-eslint/ban-tslint-comment',
  '@typescript-eslint/ban-types',
  '@typescript-eslint/class-literal-property-style',
  '@typescript-eslint/consistent-generic-constructors',
  '@typescript-eslint/consistent-indexed-object-style',
  '@typescript-eslint/consistent-return',
  '@typescript-eslint/consistent-type-assertions',
  '@typescript-eslint/consistent-type-definitions',
  '@typescript-eslint/consistent-type-exports',
  '@typescript-eslint/consistent-type-imports',
  '@typescript-eslint/dot-notation',
  '@typescript-eslint/explicit-function-return-type',
  '@typescript-eslint/explicit-member-accessibility',
  '@typescript-eslint/explicit-module-boundary-types',
  '@typescript-eslint/no-array-delete',
  '@typescript-eslint/no-base-to-string',
  '@typescript-eslint/no-confusing-non-null-assertion',
  '@typescript-eslint/no-confusing-void-expression',
  '@typescript-eslint/no-deprecated',
  '@typescript-eslint/no-duplicate-enum-values',
  '@typescript-eslint/no-duplicate-type-constituents',
  '@typescript-eslint/no-dynamic-delete',
  '@typescript-eslint/no-empty-interface',
  '@typescript-eslint/no-empty-object-type',
  '@typescript-eslint/no-explicit-any',
  '@typescript-eslint/no-extra-non-null-assertion',
  '@typescript-eslint/no-extraneous-class',
  '@typescript-eslint/no-floating-promises',
  '@typescript-eslint/no-for-in-array',
  '@typescript-eslint/no-implied-eval',
  '@typescript-eslint/no-import-type-side-effects',
  '@typescript-eslint/no-inferrable-types',
  '@typescript-eslint/no-invalid-void-type',
  '@typescript-eslint/no-meaningless-void-operator',
  '@typescript-eslint/no-misused-new',
  '@typescript-eslint/no-misused-promises',
  '@typescript-eslint/no-misused-spread',
  '@typescript-eslint/no-mixed-enums',
  '@typescript-eslint/no-namespace',
  '@typescript-eslint/no-non-null-asserted-nullish-coalescing',
  '@typescript-eslint/no-non-null-asserted-optional-chain',
  '@typescript-eslint/no-non-null-assertion',
  '@typescript-eslint/no-redundant-type-constituents',
  '@typescript-eslint/no-require-imports',
  '@typescript-eslint/no-restricted-types',
  '@typescript-eslint/no-this-alias',
  '@typescript-eslint/no-unnecessary-boolean-literal-compare',
  '@typescript-eslint/no-unnecessary-condition',
  '@typescript-eslint/no-unnecessary-parameter-property-assignment',
  '@typescript-eslint/no-unnecessary-qualifier',
  '@typescript-eslint/no-unnecessary-template-expression',
  '@typescript-eslint/no-unnecessary-type-arguments',
  '@typescript-eslint/no-unnecessary-type-assertion',
  '@typescript-eslint/no-unnecessary-type-constraint',
  '@typescript-eslint/no-unnecessary-type-conversion',
  '@typescript-eslint/no-unnecessary-type-parameters',
  '@typescript-eslint/no-unsafe-argument',
  '@typescript-eslint/no-unsafe-assignment',
  '@typescript-eslint/no-unsafe-call',
  '@typescript-eslint/no-unsafe-declaration-merging',
  '@typescript-eslint/no-unsafe-enum-comparison',
  '@typescript-eslint/no-unsafe-function-type',
  '@typescript-eslint/no-unsafe-member-access',
  '@typescript-eslint/no-unsafe-return',
  '@typescript-eslint/no-unsafe-type-assertion',
  '@typescript-eslint/no-unsafe-unary-minus',
  '@typescript-eslint/no-useless-default-assignment',
  '@typescript-eslint/no-useless-empty-export',
  '@typescript-eslint/no-var-requires',
  '@typescript-eslint/no-wrapper-object-types',
  '@typescript-eslint/non-nullable-type-assertion-style',
  '@typescript-eslint/only-throw-error',
  '@typescript-eslint/parameter-properties',
  '@typescript-eslint/prefer-as-const',
  '@typescript-eslint/prefer-enum-initializers',
  '@typescript-eslint/prefer-find',
  '@typescript-eslint/prefer-for-of',
  '@typescript-eslint/prefer-function-type',
  '@typescript-eslint/prefer-includes',
  '@typescript-eslint/prefer-literal-enum-member',
  '@typescript-eslint/prefer-namespace-keyword',
  '@typescript-eslint/prefer-nullish-coalescing',
  '@typescript-eslint/prefer-optional-chain',
  '@typescript-eslint/prefer-promise-reject-errors',
  '@typescript-eslint/prefer-readonly',
  '@typescript-eslint/prefer-readonly-parameter-types',
  '@typescript-eslint/prefer-reduce-type-parameter',
  '@typescript-eslint/prefer-regexp-exec',
  '@typescript-eslint/prefer-return-this-type',
  '@typescript-eslint/prefer-string-starts-ends-with',
  '@typescript-eslint/prefer-ts-expect-error',
  '@typescript-eslint/promise-function-async',
  '@typescript-eslint/related-getter-setter-pairs',
  '@typescript-eslint/require-array-sort-compare',
  '@typescript-eslint/require-await',
  '@typescript-eslint/restrict-plus-operands',
  '@typescript-eslint/restrict-template-expressions',
  '@typescript-eslint/return-await',
  '@typescript-eslint/strict-boolean-expressions',
  '@typescript-eslint/strict-void-return',
  '@typescript-eslint/switch-exhaustiveness-check',
  '@typescript-eslint/triple-slash-reference',
  '@typescript-eslint/unbound-method',
  '@typescript-eslint/unified-signatures',
  '@typescript-eslint/use-unknown-in-catch-callback-variable',
  'accessor-pairs',
  'array-callback-return',
  'arrow-body-style',
  'block-scoped-var',
  'capitalized-comments',
  'class-methods-use-this',
  'complexity',
  'constructor-super',
  'curly',
  'default-case',
  'default-case-last',
  'default-param-last',
  'eqeqeq',
  'eslint/accessor-pairs',
  'eslint/array-callback-return',
  'eslint/arrow-body-style',
  'eslint/block-scoped-var',
  'eslint/capitalized-comments',
  'eslint/class-methods-use-this',
  'eslint/complexity',
  'eslint/constructor-super',
  'eslint/curly',
  'eslint/default-case',
  'eslint/default-case-last',
  'eslint/default-param-last',
  'eslint/eqeqeq',
  'eslint/for-direction',
  'eslint/func-name-matching',
  'eslint/func-names',
  'eslint/func-style',
  'eslint/getter-return',
  'eslint/grouped-accessor-pairs',
  'eslint/guard-for-in',
  'eslint/id-length',
  'eslint/init-declarations',
  'eslint/logical-assignment-operators',
  'eslint/max-classes-per-file',
  'eslint/max-depth',
  'eslint/max-lines',
  'eslint/max-lines-per-function',
  'eslint/max-nested-callbacks',
  'eslint/max-params',
  'eslint/max-statements',
  'eslint/new-cap',
  'eslint/no-alert',
  'eslint/no-array-constructor',
  'eslint/no-async-promise-executor',
  'eslint/no-await-in-loop',
  'eslint/no-bitwise',
  'eslint/no-caller',
  'eslint/no-case-declarations',
  'eslint/no-class-assign',
  'eslint/no-compare-neg-zero',
  'eslint/no-cond-assign',
  'eslint/no-console',
  'eslint/no-const-assign',
  'eslint/no-constant-binary-expression',
  'eslint/no-constant-condition',
  'eslint/no-constructor-return',
  'eslint/no-continue',
  'eslint/no-control-regex',
  'eslint/no-debugger',
  'eslint/no-delete-var',
  'eslint/no-div-regex',
  'eslint/no-dupe-class-members',
  'eslint/no-dupe-else-if',
  'eslint/no-dupe-keys',
  'eslint/no-duplicate-case',
  'eslint/no-duplicate-imports',
  'eslint/no-else-return',
  'eslint/no-empty',
  'eslint/no-empty-character-class',
  'eslint/no-empty-function',
  'eslint/no-empty-pattern',
  'eslint/no-empty-static-block',
  'eslint/no-eq-null',
  'eslint/no-eval',
  'eslint/no-ex-assign',
  'eslint/no-extend-native',
  'eslint/no-extra-bind',
  'eslint/no-extra-boolean-cast',
  'eslint/no-extra-label',
  'eslint/no-fallthrough',
  'eslint/no-func-assign',
  'eslint/no-global-assign',
  'eslint/no-implicit-coercion',
  'eslint/no-import-assign',
  'eslint/no-inline-comments',
  'eslint/no-inner-declarations',
  'eslint/no-invalid-regexp',
  'eslint/no-irregular-whitespace',
  'eslint/no-iterator',
  'eslint/no-label-var',
  'eslint/no-labels',
  'eslint/no-lone-blocks',
  'eslint/no-lonely-if',
  'eslint/no-loop-func',
  'eslint/no-loss-of-precision',
  'eslint/no-magic-numbers',
  'eslint/no-misleading-character-class',
  'eslint/no-multi-assign',
  'eslint/no-multi-str',
  'eslint/no-negated-condition',
  'eslint/no-nested-ternary',
  'eslint/no-new',
  'eslint/no-new-func',
  'eslint/no-new-native-nonconstructor',
  'eslint/no-new-wrappers',
  'eslint/no-nonoctal-decimal-escape',
  'eslint/no-obj-calls',
  'eslint/no-object-constructor',
  'eslint/no-param-reassign',
  'eslint/no-plusplus',
  'eslint/no-promise-executor-return',
  'eslint/no-proto',
  'eslint/no-prototype-builtins',
  'eslint/no-redeclare',
  'eslint/no-regex-spaces',
  'eslint/no-restricted-exports',
  'eslint/no-restricted-globals',
  'eslint/no-restricted-imports',
  'eslint/no-restricted-properties',
  'eslint/no-return-assign',
  'eslint/no-script-url',
  'eslint/no-self-assign',
  'eslint/no-self-compare',
  'eslint/no-sequences',
  'eslint/no-setter-return',
  'eslint/no-shadow',
  'eslint/no-shadow-restricted-names',
  'eslint/no-sparse-arrays',
  'eslint/no-template-curly-in-string',
  'eslint/no-ternary',
  'eslint/no-this-before-super',
  'eslint/no-throw-literal',
  'eslint/no-unassigned-vars',
  'eslint/no-undef',
  'eslint/no-undefined',
  'eslint/no-underscore-dangle',
  'eslint/no-unexpected-multiline',
  'eslint/no-unmodified-loop-condition',
  'eslint/no-unneeded-ternary',
  'eslint/no-unreachable',
  'eslint/no-unsafe-finally',
  'eslint/no-unsafe-negation',
  'eslint/no-unsafe-optional-chaining',
  'eslint/no-unused-expressions',
  'eslint/no-unused-labels',
  'eslint/no-unused-private-class-members',
  'eslint/no-unused-vars',
  'eslint/no-use-before-define',
  'eslint/no-useless-assignment',
  'eslint/no-useless-backreference',
  'eslint/no-useless-call',
  'eslint/no-useless-catch',
  'eslint/no-useless-computed-key',
  'eslint/no-useless-concat',
  'eslint/no-useless-constructor',
  'eslint/no-useless-escape',
  'eslint/no-useless-rename',
  'eslint/no-useless-return',
  'eslint/no-var',
  'eslint/no-void',
  'eslint/no-warning-comments',
  'eslint/no-with',
  'eslint/object-shorthand',
  'eslint/operator-assignment',
  'eslint/prefer-const',
  'eslint/prefer-destructuring',
  'eslint/prefer-exponentiation-operator',
  'eslint/prefer-numeric-literals',
  'eslint/prefer-object-has-own',
  'eslint/prefer-object-spread',
  'eslint/prefer-promise-reject-errors',
  'eslint/prefer-rest-params',
  'eslint/prefer-spread',
  'eslint/prefer-template',
  'eslint/preserve-caught-error',
  'eslint/radix',
  'eslint/require-await',
  'eslint/require-unicode-regexp',
  'eslint/require-yield',
  'eslint/sort-imports',
  'eslint/sort-keys',
  'eslint/sort-vars',
  'eslint/symbol-description',
  'eslint/unicode-bom',
  'eslint/use-isnan',
  'eslint/valid-typeof',
  'eslint/vars-on-top',
  'eslint/yoda',
  'for-direction',
  'func-name-matching',
  'func-names',
  'func-style',
  'getter-return',
  'grouped-accessor-pairs',
  'guard-for-in',
  'id-length',
  'import/consistent-type-specifier-style',
  'import/default',
  'import/export',
  'import/exports-last',
  'import/extensions',
  'import/first',
  'import/group-exports',
  'import/max-dependencies',
  'import/named',
  'import/namespace',
  'import/no-absolute-path',
  'import/no-amd',
  'import/no-anonymous-default-export',
  'import/no-commonjs',
  'import/no-cycle',
  'import/no-default-export',
  'import/no-duplicates',
  'import/no-dynamic-require',
  'import/no-empty-named-blocks',
  'import/no-mutable-exports',
  'import/no-named-as-default',
  'import/no-named-as-default-member',
  'import/no-named-default',
  'import/no-named-export',
  'import/no-namespace',
  'import/no-nodejs-modules',
  'import/no-relative-parent-imports',
  'import/no-self-import',
  'import/no-unassigned-import',
  'import/no-webpack-loader-syntax',
  'import/prefer-default-export',
  'import/unambiguous',
  'init-declarations',
  'jest/consistent-test-it',
  'jest/expect-expect',
  'jest/max-expects',
  'jest/max-nested-describe',
  'jest/no-alias-methods',
  'jest/no-commented-out-tests',
  'jest/no-conditional-expect',
  'jest/no-conditional-in-test',
  'jest/no-confusing-set-timeout',
  'jest/no-deprecated-functions',
  'jest/no-disabled-tests',
  'jest/no-done-callback',
  'jest/no-duplicate-hooks',
  'jest/no-export',
  'jest/no-focused-tests',
  'jest/no-hooks',
  'jest/no-identical-title',
  'jest/no-interpolation-in-snapshots',
  'jest/no-jasmine-globals',
  'jest/no-large-snapshots',
  'jest/no-mocks-import',
  'jest/no-restricted-jest-methods',
  'jest/no-restricted-matchers',
  'jest/no-standalone-expect',
  'jest/no-test-prefixes',
  'jest/no-test-return-statement',
  'jest/no-unneeded-async-expect-function',
  'jest/no-untyped-mock-factory',
  'jest/padding-around-after-all-blocks',
  'jest/padding-around-test-blocks',
  'jest/prefer-called-with',
  'jest/prefer-comparison-matcher',
  'jest/prefer-each',
  'jest/prefer-ending-with-an-expect',
  'jest/prefer-equality-matcher',
  'jest/prefer-expect-assertions',
  'jest/prefer-expect-resolves',
  'jest/prefer-hooks-in-order',
  'jest/prefer-hooks-on-top',
  'jest/prefer-importing-jest-globals',
  'jest/prefer-jest-mocked',
  'jest/prefer-lowercase-title',
  'jest/prefer-mock-promise-shorthand',
  'jest/prefer-mock-return-shorthand',
  'jest/prefer-snapshot-hint',
  'jest/prefer-spy-on',
  'jest/prefer-strict-equal',
  'jest/prefer-to-be',
  'jest/prefer-to-contain',
  'jest/prefer-to-have-been-called',
  'jest/prefer-to-have-been-called-times',
  'jest/prefer-to-have-length',
  'jest/prefer-todo',
  'jest/require-hook',
  'jest/require-to-throw-message',
  'jest/require-top-level-describe',
  'jest/valid-describe-callback',
  'jest/valid-expect',
  'jest/valid-expect-in-promise',
  'jest/valid-title',
  'jsdoc/check-access',
  'jsdoc/check-property-names',
  'jsdoc/check-tag-names',
  'jsdoc/empty-tags',
  'jsdoc/implements-on-classes',
  'jsdoc/no-defaults',
  'jsdoc/require-param',
  'jsdoc/require-param-description',
  'jsdoc/require-param-name',
  'jsdoc/require-param-type',
  'jsdoc/require-property',
  'jsdoc/require-property-description',
  'jsdoc/require-property-name',
  'jsdoc/require-property-type',
  'jsdoc/require-returns',
  'jsdoc/require-returns-description',
  'jsdoc/require-returns-type',
  'jsdoc/require-yields',
  'jsx-a11y/alt-text',
  'jsx-a11y/anchor-ambiguous-text',
  'jsx-a11y/anchor-has-content',
  'jsx-a11y/anchor-is-valid',
  'jsx-a11y/aria-activedescendant-has-tabindex',
  'jsx-a11y/aria-props',
  'jsx-a11y/aria-proptypes',
  'jsx-a11y/aria-role',
  'jsx-a11y/aria-unsupported-elements',
  'jsx-a11y/autocomplete-valid',
  'jsx-a11y/click-events-have-key-events',
  'jsx-a11y/heading-has-content',
  'jsx-a11y/html-has-lang',
  'jsx-a11y/iframe-has-title',
  'jsx-a11y/img-redundant-alt',
  'jsx-a11y/interactive-supports-focus',
  'jsx-a11y/label-has-associated-control',
  'jsx-a11y/lang',
  'jsx-a11y/media-has-caption',
  'jsx-a11y/mouse-events-have-key-events',
  'jsx-a11y/no-access-key',
  'jsx-a11y/no-aria-hidden-on-focusable',
  'jsx-a11y/no-autofocus',
  'jsx-a11y/no-distracting-elements',
  'jsx-a11y/no-noninteractive-tabindex',
  'jsx-a11y/no-redundant-roles',
  'jsx-a11y/no-static-element-interactions',
  'jsx-a11y/prefer-tag-over-role',
  'jsx-a11y/role-has-required-aria-props',
  'jsx-a11y/role-supports-aria-props',
  'jsx-a11y/scope',
  'jsx-a11y/tabindex-no-positive',
  'logical-assignment-operators',
  'max-classes-per-file',
  'max-depth',
  'max-lines',
  'max-lines-per-function',
  'max-nested-callbacks',
  'max-params',
  'max-statements',
  'new-cap',
  'nextjs/google-font-display',
  'nextjs/google-font-preconnect',
  'nextjs/inline-script-id',
  'nextjs/next-script-for-ga',
  'nextjs/no-assign-module-variable',
  'nextjs/no-async-client-component',
  'nextjs/no-before-interactive-script-outside-document',
  'nextjs/no-css-tags',
  'nextjs/no-document-import-in-page',
  'nextjs/no-duplicate-head',
  'nextjs/no-head-element',
  'nextjs/no-head-import-in-document',
  'nextjs/no-html-link-for-pages',
  'nextjs/no-img-element',
  'nextjs/no-page-custom-font',
  'nextjs/no-script-component-in-head',
  'nextjs/no-styled-jsx-in-document',
  'nextjs/no-sync-scripts',
  'nextjs/no-title-in-document-head',
  'nextjs/no-typos',
  'nextjs/no-unwanted-polyfillio',
  'no-alert',
  'no-array-constructor',
  'no-async-promise-executor',
  'no-await-in-loop',
  'no-bitwise',
  'no-caller',
  'no-case-declarations',
  'no-class-assign',
  'no-compare-neg-zero',
  'no-cond-assign',
  'no-console',
  'no-const-assign',
  'no-constant-binary-expression',
  'no-constant-condition',
  'no-constructor-return',
  'no-continue',
  'no-control-regex',
  'no-debugger',
  'no-delete-var',
  'no-div-regex',
  'no-dupe-class-members',
  'no-dupe-else-if',
  'no-dupe-keys',
  'no-duplicate-case',
  'no-duplicate-imports',
  'no-else-return',
  'no-empty',
  'no-empty-character-class',
  'no-empty-function',
  'no-empty-pattern',
  'no-empty-static-block',
  'no-eq-null',
  'no-eval',
  'no-ex-assign',
  'no-extend-native',
  'no-extra-bind',
  'no-extra-boolean-cast',
  'no-extra-label',
  'no-fallthrough',
  'no-func-assign',
  'no-global-assign',
  'no-implicit-coercion',
  'no-import-assign',
  'no-inline-comments',
  'no-inner-declarations',
  'no-invalid-regexp',
  'no-irregular-whitespace',
  'no-iterator',
  'no-label-var',
  'no-labels',
  'no-lone-blocks',
  'no-lonely-if',
  'no-loop-func',
  'no-loss-of-precision',
  'no-magic-numbers',
  'no-misleading-character-class',
  'no-multi-assign',
  'no-multi-str',
  'no-negated-condition',
  'no-nested-ternary',
  'no-new',
  'no-new-func',
  'no-new-native-nonconstructor',
  'no-new-wrappers',
  'no-nonoctal-decimal-escape',
  'no-obj-calls',
  'no-object-constructor',
  'no-param-reassign',
  'no-plusplus',
  'no-promise-executor-return',
  'no-proto',
  'no-prototype-builtins',
  'no-redeclare',
  'no-regex-spaces',
  'no-restricted-exports',
  'no-restricted-globals',
  'no-restricted-imports',
  'no-restricted-properties',
  'no-return-assign',
  'no-script-url',
  'no-self-assign',
  'no-self-compare',
  'no-sequences',
  'no-setter-return',
  'no-shadow',
  'no-shadow-restricted-names',
  'no-sparse-arrays',
  'no-template-curly-in-string',
  'no-ternary',
  'no-this-before-super',
  'no-throw-literal',
  'no-unassigned-vars',
  'no-undef',
  'no-undefined',
  'no-underscore-dangle',
  'no-unexpected-multiline',
  'no-unmodified-loop-condition',
  'no-unneeded-ternary',
  'no-unreachable',
  'no-unsafe-finally',
  'no-unsafe-negation',
  'no-unsafe-optional-chaining',
  'no-unused-expressions',
  'no-unused-labels',
  'no-unused-private-class-members',
  'no-unused-vars',
  'no-use-before-define',
  'no-useless-assignment',
  'no-useless-backreference',
  'no-useless-call',
  'no-useless-catch',
  'no-useless-computed-key',
  'no-useless-concat',
  'no-useless-constructor',
  'no-useless-escape',
  'no-useless-rename',
  'no-useless-return',
  'no-var',
  'no-void',
  'no-warning-comments',
  'no-with',
  'node/global-require',
  'node/handle-callback-err',
  'node/no-exports-assign',
  'node/no-new-require',
  'node/no-path-concat',
  'node/no-process-env',
  'object-shorthand',
  'operator-assignment',
  'oxc/approx-constant',
  'oxc/bad-array-method-on-arguments',
  'oxc/bad-bitwise-operator',
  'oxc/bad-char-at-comparison',
  'oxc/bad-comparison-sequence',
  'oxc/bad-min-max-func',
  'oxc/bad-object-literal-comparison',
  'oxc/bad-replace-all-arg',
  'oxc/branches-sharing-code',
  'oxc/const-comparisons',
  'oxc/double-comparisons',
  'oxc/erasing-op',
  'oxc/misrefactored-assign-op',
  'oxc/missing-throw',
  'oxc/no-accumulating-spread',
  'oxc/no-async-await',
  'oxc/no-async-endpoint-handlers',
  'oxc/no-barrel-file',
  'oxc/no-const-enum',
  'oxc/no-map-spread',
  'oxc/no-optional-chaining',
  'oxc/no-rest-spread-properties',
  'oxc/no-this-in-exported-function',
  'oxc/number-arg-out-of-range',
  'oxc/only-used-in-recursion',
  'oxc/uninvoked-array-callback',
  'prefer-const',
  'prefer-destructuring',
  'prefer-exponentiation-operator',
  'prefer-numeric-literals',
  'prefer-object-has-own',
  'prefer-object-spread',
  'prefer-promise-reject-errors',
  'prefer-rest-params',
  'prefer-spread',
  'prefer-template',
  'preserve-caught-error',
  'promise/always-return',
  'promise/avoid-new',
  'promise/catch-or-return',
  'promise/no-callback-in-promise',
  'promise/no-multiple-resolved',
  'promise/no-nesting',
  'promise/no-new-statics',
  'promise/no-promise-in-callback',
  'promise/no-return-in-finally',
  'promise/no-return-wrap',
  'promise/param-names',
  'promise/prefer-await-to-callbacks',
  'promise/prefer-await-to-then',
  'promise/prefer-catch',
  'promise/spec-only',
  'promise/valid-params',
  'radix',
  'react-perf/jsx-no-jsx-as-prop',
  'react-perf/jsx-no-new-array-as-prop',
  'react-perf/jsx-no-new-function-as-prop',
  'react-perf/jsx-no-new-object-as-prop',
  'react/button-has-type',
  'react/checked-requires-onchange-or-readonly',
  'react/display-name',
  'react/exhaustive-deps',
  'react/forbid-component-props',
  'react/forbid-dom-props',
  'react/forbid-elements',
  'react/forward-ref-uses-ref',
  'react/hook-use-state',
  'react/iframe-missing-sandbox',
  'react/jsx-boolean-value',
  'react/jsx-curly-brace-presence',
  'react/jsx-filename-extension',
  'react/jsx-fragments',
  'react/jsx-handler-names',
  'react/jsx-key',
  'react/jsx-max-depth',
  'react/jsx-no-comment-textnodes',
  'react/jsx-no-constructed-context-values',
  'react/jsx-no-duplicate-props',
  'react/jsx-no-script-url',
  'react/jsx-no-target-blank',
  'react/jsx-no-undef',
  'react/jsx-no-useless-fragment',
  'react/jsx-pascal-case',
  'react/jsx-props-no-spread-multi',
  'react/jsx-props-no-spreading',
  'react/no-array-index-key',
  'react/no-children-prop',
  'react/no-clone-element',
  'react/no-danger',
  'react/no-danger-with-children',
  'react/no-did-mount-set-state',
  'react/no-did-update-set-state',
  'react/no-direct-mutation-state',
  'react/no-find-dom-node',
  'react/no-is-mounted',
  'react/no-multi-comp',
  'react/no-namespace',
  'react/no-react-children',
  'react/no-redundant-should-component-update',
  'react/no-render-return-value',
  'react/no-set-state',
  'react/no-string-refs',
  'react/no-this-in-sfc',
  'react/no-unescaped-entities',
  'react/no-unknown-property',
  'react/no-unsafe',
  'react/no-will-update-set-state',
  'react/only-export-components',
  'react/prefer-es6-class',
  'react/prefer-function-component',
  'react/react-in-jsx-scope',
  'react/require-render-return',
  'react/rules-of-hooks',
  'react/self-closing-comp',
  'react/state-in-constructor',
  'react/style-prop-object',
  'react/void-dom-elements-no-children',
  'require-await',
  'require-unicode-regexp',
  'require-yield',
  'sort-imports',
  'sort-keys',
  'sort-vars',
  'symbol-description',
  'typescript/adjacent-overload-signatures',
  'typescript/array-type',
  'typescript/await-thenable',
  'typescript/ban-ts-comment',
  'typescript/ban-tslint-comment',
  'typescript/ban-types',
  'typescript/class-literal-property-style',
  'typescript/consistent-generic-constructors',
  'typescript/consistent-indexed-object-style',
  'typescript/consistent-return',
  'typescript/consistent-type-assertions',
  'typescript/consistent-type-definitions',
  'typescript/consistent-type-exports',
  'typescript/consistent-type-imports',
  'typescript/dot-notation',
  'typescript/explicit-function-return-type',
  'typescript/explicit-member-accessibility',
  'typescript/explicit-module-boundary-types',
  'typescript/no-array-delete',
  'typescript/no-base-to-string',
  'typescript/no-confusing-non-null-assertion',
  'typescript/no-confusing-void-expression',
  'typescript/no-deprecated',
  'typescript/no-duplicate-enum-values',
  'typescript/no-duplicate-type-constituents',
  'typescript/no-dynamic-delete',
  'typescript/no-empty-interface',
  'typescript/no-empty-object-type',
  'typescript/no-explicit-any',
  'typescript/no-extra-non-null-assertion',
  'typescript/no-extraneous-class',
  'typescript/no-floating-promises',
  'typescript/no-for-in-array',
  'typescript/no-implied-eval',
  'typescript/no-import-type-side-effects',
  'typescript/no-inferrable-types',
  'typescript/no-invalid-void-type',
  'typescript/no-meaningless-void-operator',
  'typescript/no-misused-new',
  'typescript/no-misused-promises',
  'typescript/no-misused-spread',
  'typescript/no-mixed-enums',
  'typescript/no-namespace',
  'typescript/no-non-null-asserted-nullish-coalescing',
  'typescript/no-non-null-asserted-optional-chain',
  'typescript/no-non-null-assertion',
  'typescript/no-redundant-type-constituents',
  'typescript/no-require-imports',
  'typescript/no-restricted-types',
  'typescript/no-this-alias',
  'typescript/no-unnecessary-boolean-literal-compare',
  'typescript/no-unnecessary-condition',
  'typescript/no-unnecessary-parameter-property-assignment',
  'typescript/no-unnecessary-qualifier',
  'typescript/no-unnecessary-template-expression',
  'typescript/no-unnecessary-type-arguments',
  'typescript/no-unnecessary-type-assertion',
  'typescript/no-unnecessary-type-constraint',
  'typescript/no-unnecessary-type-conversion',
  'typescript/no-unnecessary-type-parameters',
  'typescript/no-unsafe-argument',
  'typescript/no-unsafe-assignment',
  'typescript/no-unsafe-call',
  'typescript/no-unsafe-declaration-merging',
  'typescript/no-unsafe-enum-comparison',
  'typescript/no-unsafe-function-type',
  'typescript/no-unsafe-member-access',
  'typescript/no-unsafe-return',
  'typescript/no-unsafe-type-assertion',
  'typescript/no-unsafe-unary-minus',
  'typescript/no-useless-default-assignment',
  'typescript/no-useless-empty-export',
  'typescript/no-var-requires',
  'typescript/no-wrapper-object-types',
  'typescript/non-nullable-type-assertion-style',
  'typescript/only-throw-error',
  'typescript/parameter-properties',
  'typescript/prefer-as-const',
  'typescript/prefer-enum-initializers',
  'typescript/prefer-find',
  'typescript/prefer-for-of',
  'typescript/prefer-function-type',
  'typescript/prefer-includes',
  'typescript/prefer-literal-enum-member',
  'typescript/prefer-namespace-keyword',
  'typescript/prefer-nullish-coalescing',
  'typescript/prefer-optional-chain',
  'typescript/prefer-promise-reject-errors',
  'typescript/prefer-readonly',
  'typescript/prefer-readonly-parameter-types',
  'typescript/prefer-reduce-type-parameter',
  'typescript/prefer-regexp-exec',
  'typescript/prefer-return-this-type',
  'typescript/prefer-string-starts-ends-with',
  'typescript/prefer-ts-expect-error',
  'typescript/promise-function-async',
  'typescript/related-getter-setter-pairs',
  'typescript/require-array-sort-compare',
  'typescript/require-await',
  'typescript/restrict-plus-operands',
  'typescript/restrict-template-expressions',
  'typescript/return-await',
  'typescript/strict-boolean-expressions',
  'typescript/strict-void-return',
  'typescript/switch-exhaustiveness-check',
  'typescript/triple-slash-reference',
  'typescript/unbound-method',
  'typescript/unified-signatures',
  'typescript/use-unknown-in-catch-callback-variable',
  'unicode-bom',
  'unicorn/catch-error-name',
  'unicorn/consistent-assert',
  'unicorn/consistent-date-clone',
  'unicorn/consistent-empty-array-spread',
  'unicorn/consistent-existence-index-check',
  'unicorn/consistent-function-scoping',
  'unicorn/consistent-template-literal-escape',
  'unicorn/custom-error-definition',
  'unicorn/empty-brace-spaces',
  'unicorn/error-message',
  'unicorn/escape-case',
  'unicorn/explicit-length-check',
  'unicorn/filename-case',
  'unicorn/new-for-builtins',
  'unicorn/no-abusive-eslint-disable',
  'unicorn/no-accessor-recursion',
  'unicorn/no-anonymous-default-export',
  'unicorn/no-array-callback-reference',
  'unicorn/no-array-for-each',
  'unicorn/no-array-method-this-argument',
  'unicorn/no-array-reduce',
  'unicorn/no-array-reverse',
  'unicorn/no-array-sort',
  'unicorn/no-await-expression-member',
  'unicorn/no-await-in-promise-methods',
  'unicorn/no-console-spaces',
  'unicorn/no-document-cookie',
  'unicorn/no-empty-file',
  'unicorn/no-hex-escape',
  'unicorn/no-immediate-mutation',
  'unicorn/no-instanceof-array',
  'unicorn/no-instanceof-builtins',
  'unicorn/no-invalid-fetch-options',
  'unicorn/no-invalid-remove-event-listener',
  'unicorn/no-length-as-slice-end',
  'unicorn/no-lonely-if',
  'unicorn/no-magic-array-flat-depth',
  'unicorn/no-negated-condition',
  'unicorn/no-negation-in-equality-check',
  'unicorn/no-nested-ternary',
  'unicorn/no-new-array',
  'unicorn/no-new-buffer',
  'unicorn/no-null',
  'unicorn/no-object-as-default-parameter',
  'unicorn/no-process-exit',
  'unicorn/no-single-promise-in-promise-methods',
  'unicorn/no-static-only-class',
  'unicorn/no-thenable',
  'unicorn/no-this-assignment',
  'unicorn/no-typeof-undefined',
  'unicorn/no-unnecessary-array-flat-depth',
  'unicorn/no-unnecessary-array-splice-count',
  'unicorn/no-unnecessary-await',
  'unicorn/no-unnecessary-slice-end',
  'unicorn/no-unreadable-array-destructuring',
  'unicorn/no-unreadable-iife',
  'unicorn/no-useless-collection-argument',
  'unicorn/no-useless-error-capture-stack-trace',
  'unicorn/no-useless-fallback-in-spread',
  'unicorn/no-useless-iterator-to-array',
  'unicorn/no-useless-length-check',
  'unicorn/no-useless-promise-resolve-reject',
  'unicorn/no-useless-spread',
  'unicorn/no-useless-switch-case',
  'unicorn/no-useless-undefined',
  'unicorn/no-zero-fractions',
  'unicorn/number-literal-case',
  'unicorn/numeric-separators-style',
  'unicorn/prefer-add-event-listener',
  'unicorn/prefer-array-find',
  'unicorn/prefer-array-flat',
  'unicorn/prefer-array-flat-map',
  'unicorn/prefer-array-index-of',
  'unicorn/prefer-array-some',
  'unicorn/prefer-at',
  'unicorn/prefer-bigint-literals',
  'unicorn/prefer-blob-reading-methods',
  'unicorn/prefer-class-fields',
  'unicorn/prefer-classlist-toggle',
  'unicorn/prefer-code-point',
  'unicorn/prefer-date-now',
  'unicorn/prefer-default-parameters',
  'unicorn/prefer-dom-node-append',
  'unicorn/prefer-dom-node-dataset',
  'unicorn/prefer-dom-node-remove',
  'unicorn/prefer-dom-node-text-content',
  'unicorn/prefer-event-target',
  'unicorn/prefer-global-this',
  'unicorn/prefer-import-meta-properties',
  'unicorn/prefer-includes',
  'unicorn/prefer-keyboard-event-key',
  'unicorn/prefer-logical-operator-over-ternary',
  'unicorn/prefer-math-min-max',
  'unicorn/prefer-math-trunc',
  'unicorn/prefer-modern-dom-apis',
  'unicorn/prefer-modern-math-apis',
  'unicorn/prefer-module',
  'unicorn/prefer-native-coercion-functions',
  'unicorn/prefer-negative-index',
  'unicorn/prefer-node-protocol',
  'unicorn/prefer-number-properties',
  'unicorn/prefer-object-from-entries',
  'unicorn/prefer-optional-catch-binding',
  'unicorn/prefer-prototype-methods',
  'unicorn/prefer-query-selector',
  'unicorn/prefer-reflect-apply',
  'unicorn/prefer-regexp-test',
  'unicorn/prefer-response-static-json',
  'unicorn/prefer-set-has',
  'unicorn/prefer-set-size',
  'unicorn/prefer-spread',
  'unicorn/prefer-string-raw',
  'unicorn/prefer-string-replace-all',
  'unicorn/prefer-string-slice',
  'unicorn/prefer-string-starts-ends-with',
  'unicorn/prefer-string-trim-start-end',
  'unicorn/prefer-structured-clone',
  'unicorn/prefer-ternary',
  'unicorn/prefer-top-level-await',
  'unicorn/prefer-type-error',
  'unicorn/relative-url-style',
  'unicorn/require-array-join-separator',
  'unicorn/require-module-attributes',
  'unicorn/require-module-specifiers',
  'unicorn/require-number-to-fixed-digits-argument',
  'unicorn/require-post-message-target-origin',
  'unicorn/switch-case-braces',
  'unicorn/switch-case-break-position',
  'unicorn/text-encoding-identifier-case',
  'unicorn/throw-new-error',
  'use-isnan',
  'valid-typeof',
  'vars-on-top',
  'vitest/consistent-each-for',
  'vitest/consistent-test-filename',
  'vitest/consistent-test-it',
  'vitest/consistent-vitest-vi',
  'vitest/expect-expect',
  'vitest/hoisted-apis-on-top',
  'vitest/max-expects',
  'vitest/max-nested-describe',
  'vitest/no-alias-methods',
  'vitest/no-commented-out-tests',
  'vitest/no-conditional-expect',
  'vitest/no-conditional-in-test',
  'vitest/no-conditional-tests',
  'vitest/no-disabled-tests',
  'vitest/no-duplicate-hooks',
  'vitest/no-focused-tests',
  'vitest/no-hooks',
  'vitest/no-identical-title',
  'vitest/no-import-node-test',
  'vitest/no-importing-vitest-globals',
  'vitest/no-interpolation-in-snapshots',
  'vitest/no-large-snapshots',
  'vitest/no-mocks-import',
  'vitest/no-restricted-matchers',
  'vitest/no-restricted-vi-methods',
  'vitest/no-standalone-expect',
  'vitest/no-test-prefixes',
  'vitest/no-test-return-statement',
  'vitest/no-unneeded-async-expect-function',
  'vitest/prefer-called-exactly-once-with',
  'vitest/prefer-called-once',
  'vitest/prefer-called-times',
  'vitest/prefer-called-with',
  'vitest/prefer-comparison-matcher',
  'vitest/prefer-describe-function-title',
  'vitest/prefer-each',
  'vitest/prefer-equality-matcher',
  'vitest/prefer-expect-assertions',
  'vitest/prefer-expect-resolves',
  'vitest/prefer-expect-type-of',
  'vitest/prefer-hooks-in-order',
  'vitest/prefer-hooks-on-top',
  'vitest/prefer-import-in-mock',
  'vitest/prefer-importing-vitest-globals',
  'vitest/prefer-lowercase-title',
  'vitest/prefer-mock-promise-shorthand',
  'vitest/prefer-mock-return-shorthand',
  'vitest/prefer-snapshot-hint',
  'vitest/prefer-spy-on',
  'vitest/prefer-strict-boolean-matchers',
  'vitest/prefer-strict-equal',
  'vitest/prefer-to-be',
  'vitest/prefer-to-be-falsy',
  'vitest/prefer-to-be-object',
  'vitest/prefer-to-be-truthy',
  'vitest/prefer-to-contain',
  'vitest/prefer-to-have-been-called-times',
  'vitest/prefer-to-have-length',
  'vitest/prefer-todo',
  'vitest/require-awaited-expect-poll',
  'vitest/require-hook',
  'vitest/require-local-test-context-for-concurrent-snapshots',
  'vitest/require-mock-type-parameters',
  'vitest/require-test-timeout',
  'vitest/require-to-throw-message',
  'vitest/require-top-level-describe',
  'vitest/valid-describe-callback',
  'vitest/valid-expect',
  'vitest/valid-expect-in-promise',
  'vitest/valid-title',
  'vitest/warn-todo',
  'vue/define-emits-declaration',
  'vue/define-props-declaration',
  'vue/define-props-destructuring',
  'vue/max-props',
  'vue/no-arrow-functions-in-watch',
  'vue/no-deprecated-data-object-declaration',
  'vue/no-deprecated-delete-set',
  'vue/no-deprecated-destroyed-lifecycle',
  'vue/no-deprecated-events-api',
  'vue/no-deprecated-model-definition',
  'vue/no-deprecated-vue-config-keycodes',
  'vue/no-export-in-script-setup',
  'vue/no-import-compiler-macros',
  'vue/no-lifecycle-after-await',
  'vue/no-multiple-slot-args',
  'vue/no-required-prop-with-default',
  'vue/no-this-in-before-route-enter',
  'vue/prefer-import-from-vue',
  'vue/require-default-export',
  'vue/require-typed-ref',
  'vue/return-in-computed-property',
  'vue/valid-define-emits',
  'vue/valid-define-props',
  'yoda',
] as const

export const RULES_BY_PLUGIN = {
  eslint: ESLINT_RULE_NAMES,
  import: IMPORT_RULE_NAMES,
  jest: JEST_RULE_NAMES,
  jsdoc: JSDOC_RULE_NAMES,
  'jsx-a11y': JSX_A11Y_RULE_NAMES,
  nextjs: NEXTJS_RULE_NAMES,
  node: NODE_RULE_NAMES,
  oxc: OXC_RULE_NAMES,
  promise: PROMISE_RULE_NAMES,
  react: REACT_RULE_NAMES,
  'react-perf': REACT_PERF_RULE_NAMES,
  typescript: TYPESCRIPT_RULE_NAMES,
  unicorn: UNICORN_RULE_NAMES,
  vitest: VITEST_RULE_NAMES,
  vue: VUE_RULE_NAMES,
} as const

export interface BuiltinRuleOptionsByName
  extends
    EslintRuleOptionsByName,
    ImportRuleOptionsByName,
    JestRuleOptionsByName,
    JsdocRuleOptionsByName,
    JsxA11yRuleOptionsByName,
    NextjsRuleOptionsByName,
    NodeRuleOptionsByName,
    OxcRuleOptionsByName,
    PromiseRuleOptionsByName,
    ReactRuleOptionsByName,
    ReactPerfRuleOptionsByName,
    TypescriptRuleOptionsByName,
    UnicornRuleOptionsByName,
    VitestRuleOptionsByName,
    VueRuleOptionsByName {
  'accessor-pairs': {
    setWithoutGet?: boolean
    getWithoutSet?: boolean
    enforceForClassMembers?: boolean
    enforceForTSTypes?: boolean
  }
  'array-callback-return': {
    checkForEach?: boolean
    allowImplicit?: boolean
    allowVoid?: boolean
  }
  'arrow-body-style': readonly [
    'as-needed' | 'always' | 'never',
    {
      requireReturnForObjectLiteral?: boolean
    },
  ]
  'block-scoped-var': never
  'capitalized-comments': readonly [
    'Always' | 'Never',
    {
      base?: {
        ignorePattern?: string
        ignoreInlineComments?: boolean
        ignoreConsecutiveComments?: boolean
      }
      line?: {
        ignorePattern?: string
        ignoreInlineComments?: boolean
        ignoreConsecutiveComments?: boolean
      }
      block?: {
        ignorePattern?: string
        ignoreInlineComments?: boolean
        ignoreConsecutiveComments?: boolean
      }
    },
  ]
  'class-methods-use-this': {
    exceptMethods?: readonly {
      name?: string
      private?: boolean
    }[]
    enforceForClassFields?: boolean
    ignoreOverrideMethods?: boolean
    ignoreClassesWithImplements?: 'all' | 'public-fields'
  }
  complexity: {
    max?: number
    variant?: 'classic' | 'modified'
  }
  'constructor-super': never
  curly: readonly [
    'all' | 'multi' | 'multi-line' | 'multi-or-nest',
    'consistent',
  ]
  'default-case': {
    commentPattern?: string
  }
  'default-case-last': never
  'default-param-last': never
  eqeqeq: readonly [
    'always' | 'smart',
    {
      null?: 'always' | 'never' | 'ignore'
    },
  ]
  'for-direction': never
  'func-name-matching': readonly [
    'always' | 'never',
    {
      considerPropertyDescriptor?: boolean
      includeCommonJSModuleExports?: boolean
    },
  ]
  'func-names': readonly [
    'always' | 'as-needed' | 'never',
    {
      generators?: 'always' | 'as-needed' | 'never'
    },
  ]
  'func-style': readonly [
    'expression' | 'declaration',
    {
      allowArrowFunctions?: boolean
      allowTypeAnnotation?: boolean
      overrides?: {
        namedExports?: 'ignore' | 'expression' | 'declaration'
      }
    },
  ]
  'getter-return': {
    allowImplicit?: boolean
  }
  'grouped-accessor-pairs': readonly [
    'anyOrder' | 'getBeforeSet' | 'setBeforeGet',
    {
      enforceForTSTypes?: boolean
    },
  ]
  'guard-for-in': never
  'id-length': {
    exceptionPatterns?: readonly string[]
    exceptions?: readonly string[]
    max?: number
    min?: number
    checkGeneric?: boolean
    properties?: 'Always' | 'Never'
  }
  'init-declarations': readonly [
    'always' | 'never',
    {
      ignoreForLoopInit?: boolean
    },
  ]
  'logical-assignment-operators': readonly [
    'always' | 'never',
    {
      enforceForIfStatements?: boolean
    },
  ]
  'max-classes-per-file': {
    max?: number
    ignoreExpressions?: boolean
  }
  'max-depth': {
    max?: number
  }
  'max-lines': {
    max?: number
    skipBlankLines?: boolean
    skipComments?: boolean
  }
  'max-lines-per-function': {
    max?: number
    skipComments?: boolean
    skipBlankLines?: boolean
    IIFEs?: boolean
  }
  'max-nested-callbacks': {
    max?: number
  }
  'max-params': {
    max?: number
    countThis?: 'always' | 'never' | 'except-void'
    countVoidThis?: boolean
  }
  'max-statements': {
    max?: number
    ignoreTopLevelFunctions?: boolean
  }
  'new-cap': {
    newIsCap?: boolean
    capIsNew?: boolean
    newIsCapExceptions?: readonly string[]
    newIsCapExceptionPattern?: string
    capIsNewExceptions?: readonly string[]
    capIsNewExceptionPattern?: string
    properties?: boolean
  }
  'no-alert': never
  'no-array-constructor': never
  'no-async-promise-executor': never
  'no-await-in-loop': never
  'no-bitwise': {
    allow?: readonly string[]
    int32Hint?: boolean
  }
  'no-caller': never
  'no-case-declarations': never
  'no-class-assign': never
  'no-compare-neg-zero': never
  'no-cond-assign': 'except-parens' | 'always'
  'no-console': {
    allow?: readonly string[]
  }
  'no-const-assign': never
  'no-constant-binary-expression': never
  'no-constant-condition': {
    checkLoops?: 'all' | 'allExceptWhileTrue' | 'none'
  }
  'no-constructor-return': never
  'no-continue': never
  'no-control-regex': never
  'no-debugger': never
  'no-delete-var': never
  'no-div-regex': never
  'no-dupe-class-members': never
  'no-dupe-else-if': never
  'no-dupe-keys': never
  'no-duplicate-case': never
  'no-duplicate-imports': {
    includeExports?: boolean
    allowSeparateTypeImports?: boolean
  }
  'no-else-return': {
    allowElseIf?: boolean
  }
  'no-empty': {
    allowEmptyCatch?: boolean
  }
  'no-empty-character-class': never
  'no-empty-function': {
    allow?: readonly (
      | 'functions'
      | 'arrowFunctions'
      | 'generatorFunctions'
      | 'methods'
      | 'generatorMethods'
      | 'getters'
      | 'setters'
      | 'constructors'
      | 'asyncFunctions'
      | 'asyncMethods'
      | 'privateConstructors'
      | 'protectedConstructors'
      | 'decoratedFunctions'
      | 'overrideMethods'
    )[]
  }
  'no-empty-pattern': {
    allowObjectPatternsAsParameters?: boolean
  }
  'no-empty-static-block': never
  'no-eq-null': never
  'no-eval': {
    allowIndirect?: boolean
  }
  'no-ex-assign': never
  'no-extend-native': {
    exceptions?: readonly string[]
  }
  'no-extra-bind': never
  'no-extra-boolean-cast': {
    enforceForInnerExpressions?: boolean
  }
  'no-extra-label': never
  'no-fallthrough': {
    commentPattern?: string
    allowEmptyCase?: boolean
    reportUnusedFallthroughComment?: boolean
  }
  'no-func-assign': never
  'no-global-assign': {
    exceptions?: readonly string[]
  }
  'no-implicit-coercion': {
    boolean?: boolean
    number?: boolean
    string?: boolean
    disallowTemplateShorthand?: boolean
    allow?: never
  }
  'no-import-assign': never
  'no-inline-comments': {
    ignorePattern?: string
  }
  'no-inner-declarations': readonly [
    'Functions' | 'Both',
    {
      blockScopedFunctions?: 'Allow' | 'Disallow'
    },
  ]
  'no-invalid-regexp': {
    allowConstructorFlags?: readonly unknown[]
  }
  'no-irregular-whitespace': {
    skipStrings?: boolean
    skipComments?: boolean
    skipRegExps?: boolean
    skipTemplates?: boolean
    skipJSXText?: boolean
  }
  'no-iterator': never
  'no-label-var': never
  'no-labels': {
    allowLoop?: boolean
    allowSwitch?: boolean
  }
  'no-lone-blocks': never
  'no-lonely-if': never
  'no-loop-func': never
  'no-loss-of-precision': never
  'no-magic-numbers': {
    ignore?: readonly unknown[]
    ignoreArrayIndexes?: boolean
    ignoreDefaultValues?: boolean
    ignoreClassFieldInitialValues?: boolean
    enforceConst?: boolean
    detectObjects?: boolean
    ignoreEnums?: boolean
    ignoreNumericLiteralTypes?: boolean
    ignoreReadonlyClassProperties?: boolean
    ignoreTypeIndexes?: boolean
  }
  'no-misleading-character-class': {
    allowEscape?: boolean
  }
  'no-multi-assign': {
    ignoreNonDeclaration?: boolean
  }
  'no-multi-str': never
  'no-negated-condition': never
  'no-nested-ternary': never
  'no-new': never
  'no-new-func': never
  'no-new-native-nonconstructor': never
  'no-new-wrappers': never
  'no-nonoctal-decimal-escape': never
  'no-obj-calls': never
  'no-object-constructor': never
  'no-param-reassign': {
    props?: boolean
    ignorePropertyModificationsFor?: unknown
    ignorePropertyModificationsForRegex?: readonly string[]
  }
  'no-plusplus': {
    allowForLoopAfterthoughts?: boolean
  }
  'no-promise-executor-return': {
    allowVoid?: boolean
  }
  'no-proto': never
  'no-prototype-builtins': never
  'no-redeclare': {
    builtinGlobals?: boolean
  }
  'no-regex-spaces': never
  'no-restricted-exports': {
    restrictedNamedExports?: unknown
    restrictedNamedExportsPattern?: string
    restrictDefaultExports?: {
      defaultFrom?: boolean
      direct?: boolean
      named?: boolean
      namedFrom?: boolean
      namespaceFrom?: boolean
    }
    hasDefaultRestrictedNamedExport?: boolean
  }
  'no-restricted-globals': {
    restrictedGlobals?: unknown
  }
  'no-restricted-imports': unknown
  'no-restricted-properties': readonly {
    object?: string
    property?: string
    message?: string
    allowObjects?: readonly string[]
    allowProperties?: readonly string[]
  }[]
  'no-return-assign': 'always' | 'except-parens'
  'no-script-url': never
  'no-self-assign': {
    props?: boolean
  }
  'no-self-compare': never
  'no-sequences': {
    allowInParentheses?: boolean
  }
  'no-setter-return': never
  'no-shadow': {
    hoist?: 'all' | 'functions' | 'functions-and-types' | 'never' | 'types'
    allow?: readonly string[]
    ignoreTypeValueShadow?: boolean
    ignoreFunctionTypeParameterNameValueShadow?: boolean
    builtinGlobals?: boolean
    ignoreOnInitialization?: boolean
  }
  'no-shadow-restricted-names': {
    reportGlobalThis?: boolean
  }
  'no-sparse-arrays': never
  'no-template-curly-in-string': never
  'no-ternary': never
  'no-this-before-super': never
  'no-throw-literal': never
  'no-unassigned-vars': never
  'no-undef': {
    typeof?: boolean
  }
  'no-undefined': never
  'no-underscore-dangle': {
    allowAfterSuper?: boolean
    allowAfterThisConstructor?: boolean
    allow?: readonly string[]
    allowAfterThis?: boolean
    allowInArrayDestructuring?: boolean
    allowInObjectDestructuring?: boolean
    allowFunctionParams?: boolean
    enforceInClassFields?: boolean
    enforceInMethodNames?: boolean
  }
  'no-unexpected-multiline': never
  'no-unmodified-loop-condition': never
  'no-unneeded-ternary': {
    defaultAssignment?: boolean
  }
  'no-unreachable': never
  'no-unsafe-finally': never
  'no-unsafe-negation': {
    enforceForOrderingRelations?: boolean
  }
  'no-unsafe-optional-chaining': {
    disallowArithmeticOperators?: boolean
  }
  'no-unused-expressions': {
    allowShortCircuit?: boolean
    allowTernary?: boolean
    allowTaggedTemplates?: boolean
    enforceForJSX?: boolean
  }
  'no-unused-labels': never
  'no-unused-private-class-members': never
  'no-unused-vars': {
    vars?: 'all' | 'local'
    varsIgnorePattern?: 'Default' | 'None'
    args?: 'after-used' | 'all' | 'none'
    argsIgnorePattern?: 'Default' | 'None'
    ignoreRestSiblings?: boolean
    caughtErrors?: boolean
    caughtErrorsIgnorePattern?: 'Default' | 'None'
    destructuredArrayIgnorePattern?: 'Default' | 'None'
    ignoreClassWithStaticInitBlock?: boolean
    ignoreUsingDeclarations?: boolean
    reportUsedIgnorePattern?: boolean
    reportVarsOnlyUsedAsTypes?: boolean
    fix?: {
      imports?: 'off' | 'suggestion' | 'fix' | 'safe-fix'
      variables?: 'off' | 'suggestion' | 'fix' | 'safe-fix'
    }
  }
  'no-use-before-define': {
    allowNamedExports?: boolean
    classes?: boolean
    enums?: boolean
    functions?: boolean
    ignoreTypeReferences?: boolean
    typedefs?: boolean
    variables?: boolean
  }
  'no-useless-assignment': never
  'no-useless-backreference': never
  'no-useless-call': never
  'no-useless-catch': never
  'no-useless-computed-key': {
    enforceForClassMembers?: boolean
  }
  'no-useless-concat': never
  'no-useless-constructor': never
  'no-useless-escape': {
    allowRegexCharacters?: readonly unknown[]
  }
  'no-useless-rename': {
    ignoreDestructuring?: boolean
    ignoreImport?: boolean
    ignoreExport?: boolean
  }
  'no-useless-return': never
  'no-var': never
  'no-void': {
    allowAsStatement?: boolean
  }
  'no-warning-comments': unknown
  'no-with': never
  'object-shorthand': readonly [
    (
      | 'always'
      | 'methods'
      | 'properties'
      | 'consistent'
      | 'consistent-as-needed'
      | 'never'
    ),
    {
      avoidQuotes?: boolean
      ignoreConstructors?: boolean
      avoidExplicitReturnArrows?: boolean
      methodsIgnorePattern?: string
    },
  ]
  'operator-assignment': 'always' | 'never'
  'prefer-const': {
    destructuring?: 'any' | 'all'
    ignoreReadBeforeAssign?: boolean
  }
  'prefer-destructuring': {
    VariableDeclarator?: {
      array?: boolean
      object?: boolean
    }
    AssignmentExpression?: {
      array?: boolean
      object?: boolean
    }
    enforceForRenamedProperties?: boolean
  }
  'prefer-exponentiation-operator': never
  'prefer-numeric-literals': never
  'prefer-object-has-own': never
  'prefer-object-spread': never
  'prefer-promise-reject-errors': {
    allowEmptyReject?: boolean
  }
  'prefer-rest-params': never
  'prefer-spread': never
  'prefer-template': never
  'preserve-caught-error': {
    requireCatchParameter?: boolean
  }
  radix: 'always' | 'as-needed'
  'require-await': never
  'require-unicode-regexp': {
    requireFlag?: 'u' | 'v'
  }
  'require-yield': never
  'sort-imports': {
    ignoreCase?: boolean
    ignoreDeclarationSort?: boolean
    ignoreMemberSort?: boolean
    allowSeparatedGroups?: boolean
    memberSyntaxSortOrder?: readonly ('None' | 'All' | 'Multiple' | 'Single')[]
  }
  'sort-keys': readonly [
    'Desc' | 'Asc',
    {
      caseSensitive?: boolean
      natural?: boolean
      minKeys?: number
      allowLineSeparatedGroups?: boolean
    },
  ]
  'sort-vars': {
    ignoreCase?: boolean
  }
  'symbol-description': never
  'unicode-bom': 'always' | 'never'
  'use-isnan': {
    enforceForSwitchCase?: boolean
    enforceForIndexOf?: boolean
  }
  'valid-typeof': {
    requireStringLiterals?: boolean
  }
  'vars-on-top': never
  yoda: readonly [
    'never' | 'always',
    {
      exceptRange?: boolean
      onlyEquality?: boolean
    },
  ]
  '@typescript-eslint/adjacent-overload-signatures': never
  '@typescript-eslint/array-type': {
    default?: 'array' | 'array-simple' | 'generic'
    readonly?: 'array' | 'array-simple' | 'generic'
  }
  '@typescript-eslint/await-thenable': never
  '@typescript-eslint/ban-ts-comment': {
    ts_expect_error?: 'allow-with-description'
    ts_ignore?: 'allow-with-description'
    ts_nocheck?: 'allow-with-description'
    ts_check?: 'allow-with-description'
    minimumDescriptionLength?: number
  }
  '@typescript-eslint/ban-tslint-comment': never
  '@typescript-eslint/ban-types': never
  '@typescript-eslint/class-literal-property-style': 'Fields' | 'Getters'
  '@typescript-eslint/consistent-generic-constructors': {
    option?: 'constructor' | 'type-annotation'
  }
  '@typescript-eslint/consistent-indexed-object-style':
    | 'record'
    | 'index-signature'
  '@typescript-eslint/consistent-return': {
    treatUndefinedAsUnspecified?: boolean
  }
  '@typescript-eslint/consistent-type-assertions': {
    assertionStyle?: 'as' | 'angle-bracket' | 'never'
    objectLiteralTypeAssertions?: 'allow' | 'allow-as-parameter' | 'never'
    arrayLiteralTypeAssertions?: 'allow' | 'allow-as-parameter' | 'never'
  }
  '@typescript-eslint/consistent-type-definitions': 'interface' | 'type'
  '@typescript-eslint/consistent-type-exports': {
    fixMixedExportsWithInlineTypeSpecifier?: boolean
  }
  '@typescript-eslint/consistent-type-imports': {
    disallowTypeAnnotations?: boolean
    fixStyle?: 'separate-type-imports' | 'inline-type-imports'
    prefer?: 'type-imports' | 'no-type-imports'
  }
  '@typescript-eslint/dot-notation': {
    allowIndexSignaturePropertyAccess?: boolean
    allowKeywords?: boolean
    allowPattern?: string
    allowPrivateClassPropertyAccess?: boolean
    allowProtectedClassPropertyAccess?: boolean
  }
  '@typescript-eslint/explicit-function-return-type': {
    allowExpressions?: boolean
    allowTypedFunctionExpressions?: boolean
    allowDirectConstAssertionInArrowFunctions?: boolean
    allowConciseArrowFunctionExpressionsStartingWithVoid?: boolean
    allowFunctionsWithoutTypeParameters?: boolean
    allowedNames?: unknown
    allowHigherOrderFunctions?: boolean
    allowIIFEs?: boolean
  }
  '@typescript-eslint/explicit-member-accessibility': {
    accessibility?: 'explicit' | 'no-public' | 'off'
    overrides?: {
      accessors?: 'explicit' | 'no-public' | 'off'
      constructors?: 'explicit' | 'no-public' | 'off'
      methods?: 'explicit' | 'no-public' | 'off'
      parameterProperties?: 'explicit' | 'no-public' | 'off'
      properties?: 'explicit' | 'no-public' | 'off'
    }
    ignoredMethodNames?: readonly string[]
  }
  '@typescript-eslint/explicit-module-boundary-types': {
    allowArgumentsExplicitlyTypedAsAny?: boolean
    allowDirectConstAssertionInArrowFunctions?: boolean
    allowedNames?: readonly string[]
    allowHigherOrderFunctions?: boolean
    allowOverloadFunctions?: boolean
    allowTypedFunctionExpressions?: boolean
  }
  '@typescript-eslint/no-array-delete': never
  '@typescript-eslint/no-base-to-string': {
    checkUnknown?: boolean
    ignoredTypeNames?: readonly string[]
  }
  '@typescript-eslint/no-confusing-non-null-assertion': never
  '@typescript-eslint/no-confusing-void-expression': {
    ignoreArrowShorthand?: boolean
    ignoreVoidOperator?: boolean
    ignoreVoidReturningFunctions?: boolean
  }
  '@typescript-eslint/no-deprecated': {
    allow?: readonly unknown[]
  }
  '@typescript-eslint/no-duplicate-enum-values': never
  '@typescript-eslint/no-duplicate-type-constituents': {
    ignoreIntersections?: boolean
    ignoreUnions?: boolean
  }
  '@typescript-eslint/no-dynamic-delete': never
  '@typescript-eslint/no-empty-interface': never
  '@typescript-eslint/no-empty-object-type': {
    allowInterfaces?: 'never' | 'always' | 'with-single-extends'
    allowObjectTypes?: 'never' | 'always'
    allowWithName?: string
  }
  '@typescript-eslint/no-explicit-any': {
    fixToUnknown?: boolean
    ignoreRestArgs?: boolean
  }
  '@typescript-eslint/no-extra-non-null-assertion': never
  '@typescript-eslint/no-extraneous-class': {
    allowConstructorOnly?: boolean
    allowEmpty?: boolean
    allowStaticOnly?: boolean
    allowWithDecorator?: boolean
  }
  '@typescript-eslint/no-floating-promises': {
    allowForKnownSafeCalls?: readonly unknown[]
    allowForKnownSafePromises?: readonly unknown[]
    checkThenables?: boolean
    ignoreIIFE?: boolean
    ignoreVoid?: boolean
  }
  '@typescript-eslint/no-for-in-array': never
  '@typescript-eslint/no-implied-eval': never
  '@typescript-eslint/no-import-type-side-effects': never
  '@typescript-eslint/no-inferrable-types': {
    ignoreParameters?: boolean
    ignoreProperties?: boolean
  }
  '@typescript-eslint/no-invalid-void-type': {
    allowAsThisParameter?: boolean
    allowInGenericTypeArguments?: unknown
  }
  '@typescript-eslint/no-meaningless-void-operator': {
    checkNever?: boolean
  }
  '@typescript-eslint/no-misused-new': never
  '@typescript-eslint/no-misused-promises': {
    checksConditionals?: boolean
    checksSpreads?: boolean
    checksVoidReturn?: unknown
  }
  '@typescript-eslint/no-misused-spread': {
    allow?: readonly unknown[]
  }
  '@typescript-eslint/no-mixed-enums': never
  '@typescript-eslint/no-namespace': {
    allowDeclarations?: boolean
    allowDefinitionFiles?: boolean
  }
  '@typescript-eslint/no-non-null-asserted-nullish-coalescing': never
  '@typescript-eslint/no-non-null-asserted-optional-chain': never
  '@typescript-eslint/no-non-null-assertion': never
  '@typescript-eslint/no-redundant-type-constituents': never
  '@typescript-eslint/no-require-imports': {
    allow?: readonly string[]
    allowAsImport?: boolean
  }
  '@typescript-eslint/no-restricted-types': {
    types?: unknown
  }
  '@typescript-eslint/no-this-alias': {
    allowDestructuring?: boolean
  }
  '@typescript-eslint/no-unnecessary-boolean-literal-compare': {
    allowComparingNullableBooleansToFalse?: boolean
    allowComparingNullableBooleansToTrue?: boolean
  }
  '@typescript-eslint/no-unnecessary-condition': {
    allowConstantLoopConditions?: unknown
    checkTypePredicates?: boolean
  }
  '@typescript-eslint/no-unnecessary-parameter-property-assignment': never
  '@typescript-eslint/no-unnecessary-qualifier': never
  '@typescript-eslint/no-unnecessary-template-expression': never
  '@typescript-eslint/no-unnecessary-type-arguments': never
  '@typescript-eslint/no-unnecessary-type-assertion': {
    checkLiteralConstAssertions?: boolean
    typesToIgnore?: readonly string[]
  }
  '@typescript-eslint/no-unnecessary-type-constraint': never
  '@typescript-eslint/no-unnecessary-type-conversion': never
  '@typescript-eslint/no-unnecessary-type-parameters': never
  '@typescript-eslint/no-unsafe-argument': never
  '@typescript-eslint/no-unsafe-assignment': never
  '@typescript-eslint/no-unsafe-call': never
  '@typescript-eslint/no-unsafe-declaration-merging': never
  '@typescript-eslint/no-unsafe-enum-comparison': never
  '@typescript-eslint/no-unsafe-function-type': never
  '@typescript-eslint/no-unsafe-member-access': {
    allowOptionalChaining?: boolean
  }
  '@typescript-eslint/no-unsafe-return': never
  '@typescript-eslint/no-unsafe-type-assertion': never
  '@typescript-eslint/no-unsafe-unary-minus': never
  '@typescript-eslint/no-useless-default-assignment': never
  '@typescript-eslint/no-useless-empty-export': never
  '@typescript-eslint/no-var-requires': never
  '@typescript-eslint/no-wrapper-object-types': never
  '@typescript-eslint/non-nullable-type-assertion-style': never
  '@typescript-eslint/only-throw-error': {
    allow?: readonly unknown[]
    allowRethrowing?: boolean
    allowThrowingAny?: boolean
    allowThrowingUnknown?: boolean
  }
  '@typescript-eslint/parameter-properties': {
    allow?: readonly (
      | 'private'
      | 'private readonly'
      | 'protected'
      | 'protected readonly'
      | 'public'
      | 'public readonly'
      | 'readonly'
    )[]
    prefer?: 'class-property' | 'parameter-property'
  }
  '@typescript-eslint/prefer-as-const': never
  '@typescript-eslint/prefer-enum-initializers': never
  '@typescript-eslint/prefer-find': never
  '@typescript-eslint/prefer-for-of': never
  '@typescript-eslint/prefer-function-type': never
  '@typescript-eslint/prefer-includes': never
  '@typescript-eslint/prefer-literal-enum-member': {
    allowBitwiseExpressions?: boolean
  }
  '@typescript-eslint/prefer-namespace-keyword': never
  '@typescript-eslint/prefer-nullish-coalescing': {
    ignoreBooleanCoercion?: boolean
    ignoreConditionalTests?: boolean
    ignoreIfStatements?: boolean
    ignoreMixedLogicalExpressions?: boolean
    ignoreTernaryTests?: boolean
    ignorePrimitives?: unknown
  }
  '@typescript-eslint/prefer-optional-chain': {
    allowPotentiallyUnsafeFixesThatModifyTheReturnTypeIKnowWhatImDoing?: boolean
    checkAny?: boolean
    checkBigInt?: boolean
    checkBoolean?: boolean
    checkNumber?: boolean
    checkString?: boolean
    checkUnknown?: boolean
    requireNullish?: boolean
  }
  '@typescript-eslint/prefer-promise-reject-errors': {
    allow?: readonly unknown[]
    allowEmptyReject?: boolean
    allowThrowingAny?: boolean
    allowThrowingUnknown?: boolean
  }
  '@typescript-eslint/prefer-readonly': {
    onlyInlineLambdas?: boolean
  }
  '@typescript-eslint/prefer-readonly-parameter-types': {
    allow?: readonly unknown[]
    checkParameterProperties?: boolean
    ignoreInferredTypes?: boolean
    treatMethodsAsReadonly?: boolean
  }
  '@typescript-eslint/prefer-reduce-type-parameter': never
  '@typescript-eslint/prefer-regexp-exec': never
  '@typescript-eslint/prefer-return-this-type': never
  '@typescript-eslint/prefer-string-starts-ends-with': {
    allowSingleElementEquality?: 'always' | 'never'
  }
  '@typescript-eslint/prefer-ts-expect-error': never
  '@typescript-eslint/promise-function-async': {
    allowAny?: boolean
    allowedPromiseNames?: readonly string[]
    checkArrowFunctions?: boolean
    checkFunctionDeclarations?: boolean
    checkFunctionExpressions?: boolean
    checkMethodDeclarations?: boolean
  }
  '@typescript-eslint/related-getter-setter-pairs': never
  '@typescript-eslint/require-array-sort-compare': {
    ignoreStringArrays?: boolean
  }
  '@typescript-eslint/require-await': never
  '@typescript-eslint/restrict-plus-operands': {
    allowAny?: boolean
    allowBoolean?: boolean
    allowNullish?: boolean
    allowNumberAndString?: boolean
    allowRegExp?: boolean
    skipCompoundAssignments?: boolean
  }
  '@typescript-eslint/restrict-template-expressions': {
    allowAny?: boolean
    allowArray?: boolean
    allowBoolean?: boolean
    allowNullish?: boolean
    allowNumber?: boolean
    allowRegExp?: boolean
    allowNever?: boolean
    allow?: readonly unknown[]
  }
  '@typescript-eslint/return-await':
    | 'in-try-catch'
    | 'always'
    | 'error-handling-correctness-only'
    | 'never'
  '@typescript-eslint/strict-boolean-expressions': {
    allowAny?: boolean
    allowNullableBoolean?: boolean
    allowNullableNumber?: boolean
    allowNullableString?: boolean
    allowNullableEnum?: boolean
    allowNullableObject?: boolean
    allowString?: boolean
    allowNumber?: boolean
  }
  '@typescript-eslint/strict-void-return': {
    allowReturnAny?: boolean
  }
  '@typescript-eslint/switch-exhaustiveness-check': {
    allowDefaultCaseForExhaustiveSwitch?: boolean
    considerDefaultExhaustiveForUnions?: boolean
    defaultCaseCommentPattern?: string
    requireDefaultForNonUnion?: boolean
  }
  '@typescript-eslint/triple-slash-reference': {
    lib?: 'always' | 'never'
    path?: 'always' | 'never'
    types?: 'always' | 'never' | 'prefer-import'
  }
  '@typescript-eslint/unbound-method': {
    ignoreStatic?: boolean
  }
  '@typescript-eslint/unified-signatures': {
    ignoreDifferentlyNamedParameters?: boolean
    ignoreOverloadsWithDifferentJSDoc?: boolean
  }
  '@typescript-eslint/use-unknown-in-catch-callback-variable': never
}

export type BuiltinPluginName = (typeof BUILTIN_PLUGIN_NAMES)[number]
export type BuiltinRuleName = (typeof BUILTIN_RULE_NAMES)[number]
export type RulesByPlugin = typeof RULES_BY_PLUGIN
export type BuiltinNamespacedRuleName =
  | EslintRuleName
  | ImportRuleName
  | JestRuleName
  | JsdocRuleName
  | JsxA11yRuleName
  | NextjsRuleName
  | NodeRuleName
  | OxcRuleName
  | PromiseRuleName
  | ReactRuleName
  | ReactPerfRuleName
  | TypescriptRuleName
  | UnicornRuleName
  | VitestRuleName
  | VueRuleName
