/* oxlint-disable */
// This file is auto-generated by scripts/generate-rules.ts
// Do not edit this file directly.

export const JEST_RULE_NAMES = [
  'consistent-test-it',
  'expect-expect',
  'max-expects',
  'max-nested-describe',
  'no-alias-methods',
  'no-commented-out-tests',
  'no-conditional-expect',
  'no-conditional-in-test',
  'no-confusing-set-timeout',
  'no-deprecated-functions',
  'no-disabled-tests',
  'no-done-callback',
  'no-duplicate-hooks',
  'no-export',
  'no-focused-tests',
  'no-hooks',
  'no-identical-title',
  'no-interpolation-in-snapshots',
  'no-jasmine-globals',
  'no-large-snapshots',
  'no-mocks-import',
  'no-restricted-jest-methods',
  'no-restricted-matchers',
  'no-standalone-expect',
  'no-test-prefixes',
  'no-test-return-statement',
  'no-unneeded-async-expect-function',
  'no-untyped-mock-factory',
  'padding-around-after-all-blocks',
  'padding-around-test-blocks',
  'prefer-called-with',
  'prefer-comparison-matcher',
  'prefer-each',
  'prefer-ending-with-an-expect',
  'prefer-equality-matcher',
  'prefer-expect-assertions',
  'prefer-expect-resolves',
  'prefer-hooks-in-order',
  'prefer-hooks-on-top',
  'prefer-importing-jest-globals',
  'prefer-jest-mocked',
  'prefer-lowercase-title',
  'prefer-mock-promise-shorthand',
  'prefer-mock-return-shorthand',
  'prefer-snapshot-hint',
  'prefer-spy-on',
  'prefer-strict-equal',
  'prefer-to-be',
  'prefer-to-contain',
  'prefer-to-have-been-called',
  'prefer-to-have-been-called-times',
  'prefer-to-have-length',
  'prefer-todo',
  'require-hook',
  'require-to-throw-message',
  'require-top-level-describe',
  'valid-describe-callback',
  'valid-expect',
  'valid-expect-in-promise',
  'valid-title',
] as const

export type JestRuleName = (typeof JEST_RULE_NAMES)[number]

export interface JestRuleOptionsByName {
  'jest/consistent-test-it': unknown
  'jest/expect-expect': unknown
  'jest/max-expects': unknown
  'jest/max-nested-describe': unknown
  'jest/no-alias-methods': never
  'jest/no-commented-out-tests': never
  'jest/no-conditional-expect': never
  'jest/no-conditional-in-test': never
  'jest/no-confusing-set-timeout': never
  'jest/no-deprecated-functions': {
    jest?: {
      version?: string
    }
  }
  'jest/no-disabled-tests': never
  'jest/no-done-callback': never
  'jest/no-duplicate-hooks': never
  'jest/no-export': never
  'jest/no-focused-tests': never
  'jest/no-hooks': unknown
  'jest/no-identical-title': never
  'jest/no-interpolation-in-snapshots': never
  'jest/no-jasmine-globals': never
  'jest/no-large-snapshots': unknown
  'jest/no-mocks-import': never
  'jest/no-restricted-jest-methods': unknown
  'jest/no-restricted-matchers': unknown
  'jest/no-standalone-expect': unknown
  'jest/no-test-prefixes': never
  'jest/no-test-return-statement': never
  'jest/no-unneeded-async-expect-function': never
  'jest/no-untyped-mock-factory': never
  'jest/padding-around-after-all-blocks': never
  'jest/padding-around-test-blocks': never
  'jest/prefer-called-with': never
  'jest/prefer-comparison-matcher': never
  'jest/prefer-each': never
  'jest/prefer-ending-with-an-expect': {
    additionalTestBlockFunctions?: readonly string[]
    assertFunctionNames?: readonly string[]
  }
  'jest/prefer-equality-matcher': never
  'jest/prefer-expect-assertions': unknown
  'jest/prefer-expect-resolves': never
  'jest/prefer-hooks-in-order': never
  'jest/prefer-hooks-on-top': never
  'jest/prefer-importing-jest-globals': {
    types?: readonly (
      | 'hook'
      | 'describe'
      | 'test'
      | 'expect'
      | 'jest'
      | 'unknown'
    )[]
  }
  'jest/prefer-jest-mocked': never
  'jest/prefer-lowercase-title': unknown
  'jest/prefer-mock-promise-shorthand': never
  'jest/prefer-mock-return-shorthand': never
  'jest/prefer-snapshot-hint': unknown
  'jest/prefer-spy-on': never
  'jest/prefer-strict-equal': never
  'jest/prefer-to-be': never
  'jest/prefer-to-contain': never
  'jest/prefer-to-have-been-called': never
  'jest/prefer-to-have-been-called-times': never
  'jest/prefer-to-have-length': never
  'jest/prefer-todo': never
  'jest/require-hook': unknown
  'jest/require-to-throw-message': never
  'jest/require-top-level-describe': unknown
  'jest/valid-describe-callback': never
  'jest/valid-expect': unknown
  'jest/valid-expect-in-promise': never
  'jest/valid-title': unknown
}
