/* oxlint-disable */
// This file is auto-generated by scripts/generate-rules.ts
// Do not edit this file directly.

export const JSDOC_RULE_NAMES = [
  'check-access',
  'check-property-names',
  'check-tag-names',
  'empty-tags',
  'implements-on-classes',
  'no-defaults',
  'require-param',
  'require-param-description',
  'require-param-name',
  'require-param-type',
  'require-property',
  'require-property-description',
  'require-property-name',
  'require-property-type',
  'require-returns',
  'require-returns-description',
  'require-returns-type',
  'require-throws-description',
  'require-throws-type',
  'require-yields',
  'require-yields-description',
  'require-yields-type',
] as const

export type JsdocRuleName = (typeof JSDOC_RULE_NAMES)[number]

export interface JsdocRuleOptionsByName {
  'jsdoc/check-access': never
  'jsdoc/check-property-names': never
  'jsdoc/check-tag-names': {
    definedTags?: readonly string[]
    jsxTags?: boolean
    typed?: boolean
  }
  'jsdoc/empty-tags': {
    tags?: readonly string[]
  }
  'jsdoc/implements-on-classes': never
  'jsdoc/no-defaults': {
    noOptionalParamNames?: boolean
  }
  'jsdoc/require-param': {
    exemptedBy?: readonly string[]
    checkConstructors?: boolean
    checkGetters?: boolean
    checkSetters?: boolean
    checkDestructuredRoots?: boolean
    checkDestructured?: boolean
    checkRestProperty?: boolean
    checkTypesPattern?: string
  }
  'jsdoc/require-param-description': never
  'jsdoc/require-param-name': never
  'jsdoc/require-param-type': never
  'jsdoc/require-property': never
  'jsdoc/require-property-description': never
  'jsdoc/require-property-name': never
  'jsdoc/require-property-type': never
  'jsdoc/require-returns': {
    exemptedBy?: readonly string[]
    checkConstructors?: boolean
    checkGetters?: boolean
    forceRequireReturn?: boolean
    forceReturnsWithAsync?: boolean
  }
  'jsdoc/require-returns-description': never
  'jsdoc/require-returns-type': never
  'jsdoc/require-throws-description': unknown
  'jsdoc/require-throws-type': unknown
  'jsdoc/require-yields': {
    exemptedBy?: readonly string[]
    forceRequireYields?: boolean
    withGeneratorTag?: boolean
  }
  'jsdoc/require-yields-description': unknown
  'jsdoc/require-yields-type': unknown
}
