/* oxlint-disable */
// This file is auto-generated by scripts/generate-rules.ts
// Do not edit this file directly.

export const JSX_A11Y_RULE_NAMES = [
  'alt-text',
  'anchor-ambiguous-text',
  'anchor-has-content',
  'anchor-is-valid',
  'aria-activedescendant-has-tabindex',
  'aria-props',
  'aria-proptypes',
  'aria-role',
  'aria-unsupported-elements',
  'autocomplete-valid',
  'click-events-have-key-events',
  'control-has-associated-label',
  'heading-has-content',
  'html-has-lang',
  'iframe-has-title',
  'img-redundant-alt',
  'interactive-supports-focus',
  'label-has-associated-control',
  'lang',
  'media-has-caption',
  'mouse-events-have-key-events',
  'no-access-key',
  'no-aria-hidden-on-focusable',
  'no-autofocus',
  'no-distracting-elements',
  'no-interactive-element-to-noninteractive-role',
  'no-noninteractive-element-interactions',
  'no-noninteractive-element-to-interactive-role',
  'no-noninteractive-tabindex',
  'no-redundant-roles',
  'no-static-element-interactions',
  'prefer-tag-over-role',
  'role-has-required-aria-props',
  'role-supports-aria-props',
  'scope',
  'tabindex-no-positive',
] as const

export type JsxA11yRuleName = (typeof JSX_A11Y_RULE_NAMES)[number]

export interface JsxA11yRuleOptionsByName {
  'jsx-a11y/alt-text': {
    img?: readonly string[]
    object?: readonly string[]
    area?: readonly string[]
    'input[type="image"]'?: readonly string[]
  }
  'jsx-a11y/anchor-ambiguous-text': {
    words?: readonly string[]
  }
  'jsx-a11y/anchor-has-content': never
  'jsx-a11y/anchor-is-valid': {
    validHrefs?: readonly string[]
  }
  'jsx-a11y/aria-activedescendant-has-tabindex': never
  'jsx-a11y/aria-props': never
  'jsx-a11y/aria-proptypes': never
  'jsx-a11y/aria-role': {
    ignoreNonDOM?: boolean
    allowedInvalidRoles?: readonly string[]
  }
  'jsx-a11y/aria-unsupported-elements': never
  'jsx-a11y/autocomplete-valid': {
    inputComponents?: unknown
  }
  'jsx-a11y/click-events-have-key-events': never
  'jsx-a11y/control-has-associated-label': unknown
  'jsx-a11y/heading-has-content': {
    components?: readonly string[]
  }
  'jsx-a11y/html-has-lang': never
  'jsx-a11y/iframe-has-title': never
  'jsx-a11y/img-redundant-alt': {
    components?: readonly string[]
    words?: unknown
  }
  'jsx-a11y/interactive-supports-focus': {
    tabbable?: readonly string[]
  }
  'jsx-a11y/label-has-associated-control': {
    depth?: number
    assert?: 'htmlFor' | 'nesting' | 'both' | 'either'
    labelComponents?: readonly string[]
    labelAttributes?: readonly string[]
    controlComponents?: readonly string[]
  }
  'jsx-a11y/lang': never
  'jsx-a11y/media-has-caption': {
    audio?: readonly string[]
    track?: unknown
  }
  'jsx-a11y/mouse-events-have-key-events': {
    hoverInHandlers?: readonly string[]
    hoverOutHandlers?: readonly string[]
  }
  'jsx-a11y/no-access-key': never
  'jsx-a11y/no-aria-hidden-on-focusable': never
  'jsx-a11y/no-autofocus': {
    ignoreNonDOM?: boolean
  }
  'jsx-a11y/no-distracting-elements': {
    elements?: readonly ('Marquee' | 'Blink')[]
  }
  'jsx-a11y/no-interactive-element-to-noninteractive-role': unknown
  'jsx-a11y/no-noninteractive-element-interactions': unknown
  'jsx-a11y/no-noninteractive-element-to-interactive-role': unknown
  'jsx-a11y/no-noninteractive-tabindex': {
    tags?: readonly string[]
    roles?: readonly string[]
    allowExpressionValues?: boolean
  }
  'jsx-a11y/no-redundant-roles': never
  'jsx-a11y/no-static-element-interactions': {
    handlers?: readonly string[]
    allowExpressionValues?: boolean
  }
  'jsx-a11y/prefer-tag-over-role': never
  'jsx-a11y/role-has-required-aria-props': never
  'jsx-a11y/role-supports-aria-props': never
  'jsx-a11y/scope': never
  'jsx-a11y/tabindex-no-positive': never
}
