/* oxlint-disable */
// This file is auto-generated by scripts/generate-rules.ts
// Do not edit this file directly.

export const NEXTJS_RULE_NAMES = [
  'google-font-display',
  'google-font-preconnect',
  'inline-script-id',
  'next-script-for-ga',
  'no-assign-module-variable',
  'no-async-client-component',
  'no-before-interactive-script-outside-document',
  'no-css-tags',
  'no-document-import-in-page',
  'no-duplicate-head',
  'no-head-element',
  'no-head-import-in-document',
  'no-html-link-for-pages',
  'no-img-element',
  'no-page-custom-font',
  'no-script-component-in-head',
  'no-styled-jsx-in-document',
  'no-sync-scripts',
  'no-title-in-document-head',
  'no-typos',
  'no-unwanted-polyfillio',
] as const

export type NextjsRuleName = (typeof NEXTJS_RULE_NAMES)[number]

export interface NextjsRuleOptionsByName {
  'nextjs/google-font-display': never
  'nextjs/google-font-preconnect': never
  'nextjs/inline-script-id': never
  'nextjs/next-script-for-ga': never
  'nextjs/no-assign-module-variable': never
  'nextjs/no-async-client-component': never
  'nextjs/no-before-interactive-script-outside-document': never
  'nextjs/no-css-tags': never
  'nextjs/no-document-import-in-page': never
  'nextjs/no-duplicate-head': never
  'nextjs/no-head-element': never
  'nextjs/no-head-import-in-document': never
  'nextjs/no-html-link-for-pages': never
  'nextjs/no-img-element': never
  'nextjs/no-page-custom-font': never
  'nextjs/no-script-component-in-head': never
  'nextjs/no-styled-jsx-in-document': never
  'nextjs/no-sync-scripts': never
  'nextjs/no-title-in-document-head': never
  'nextjs/no-typos': never
  'nextjs/no-unwanted-polyfillio': never
}
