/* oxlint-disable */
// This file is auto-generated by scripts/generate-rules.ts
// Do not edit this file directly.

export const OXC_RULE_NAMES = [
  'approx-constant',
  'bad-array-method-on-arguments',
  'bad-bitwise-operator',
  'bad-char-at-comparison',
  'bad-comparison-sequence',
  'bad-min-max-func',
  'bad-object-literal-comparison',
  'bad-replace-all-arg',
  'branches-sharing-code',
  'const-comparisons',
  'double-comparisons',
  'erasing-op',
  'misrefactored-assign-op',
  'missing-throw',
  'no-accumulating-spread',
  'no-async-await',
  'no-async-endpoint-handlers',
  'no-barrel-file',
  'no-const-enum',
  'no-map-spread',
  'no-optional-chaining',
  'no-rest-spread-properties',
  'no-this-in-exported-function',
  'number-arg-out-of-range',
  'only-used-in-recursion',
  'uninvoked-array-callback',
] as const

export type OxcRuleName = (typeof OXC_RULE_NAMES)[number]

export interface OxcRuleOptionsByName {
  'oxc/approx-constant': never
  'oxc/bad-array-method-on-arguments': never
  'oxc/bad-bitwise-operator': never
  'oxc/bad-char-at-comparison': never
  'oxc/bad-comparison-sequence': never
  'oxc/bad-min-max-func': never
  'oxc/bad-object-literal-comparison': never
  'oxc/bad-replace-all-arg': never
  'oxc/branches-sharing-code': never
  'oxc/const-comparisons': never
  'oxc/double-comparisons': never
  'oxc/erasing-op': never
  'oxc/misrefactored-assign-op': never
  'oxc/missing-throw': never
  'oxc/no-accumulating-spread': never
  'oxc/no-async-await': never
  'oxc/no-async-endpoint-handlers': {
    allowedNames?: readonly string[]
  }
  'oxc/no-barrel-file': {
    threshold?: number
  }
  'oxc/no-const-enum': never
  'oxc/no-map-spread': {
    ignoreRereads?: boolean
    ignoreArgs?: boolean
  }
  'oxc/no-optional-chaining': {
    message?: string
  }
  'oxc/no-rest-spread-properties': {
    objectSpreadMessage?: string
    objectRestMessage?: string
  }
  'oxc/no-this-in-exported-function': never
  'oxc/number-arg-out-of-range': never
  'oxc/only-used-in-recursion': never
  'oxc/uninvoked-array-callback': never
}
