/* oxlint-disable */
// This file is auto-generated by scripts/generate-rules.ts
// Do not edit this file directly.

export const PROMISE_RULE_NAMES = [
  'always-return',
  'avoid-new',
  'catch-or-return',
  'no-callback-in-promise',
  'no-multiple-resolved',
  'no-nesting',
  'no-new-statics',
  'no-promise-in-callback',
  'no-return-in-finally',
  'no-return-wrap',
  'param-names',
  'prefer-await-to-callbacks',
  'prefer-await-to-then',
  'prefer-catch',
  'spec-only',
  'valid-params',
] as const

export type PromiseRuleName = (typeof PROMISE_RULE_NAMES)[number]

export interface PromiseRuleOptionsByName {
  'promise/always-return': {
    ignoreLastCallback?: boolean
    ignoreAssignmentVariable?: unknown
  }
  'promise/avoid-new': never
  'promise/catch-or-return': {
    allowFinally?: boolean
    allowThen?: boolean
    terminationMethod?: readonly string[]
  }
  'promise/no-callback-in-promise': {
    callbacks?: readonly string[]
    exceptions?: readonly string[]
    timeoutsErr?: boolean
  }
  'promise/no-multiple-resolved': never
  'promise/no-nesting': never
  'promise/no-new-statics': never
  'promise/no-promise-in-callback': never
  'promise/no-return-in-finally': never
  'promise/no-return-wrap': {
    allowReject?: boolean
  }
  'promise/param-names': {
    resolvePattern?: string
    rejectPattern?: string
  }
  'promise/prefer-await-to-callbacks': never
  'promise/prefer-await-to-then': {
    strict?: boolean
  }
  'promise/prefer-catch': never
  'promise/spec-only': {
    allowedMethods?: unknown
  }
  'promise/valid-params': never
}
