/* oxlint-disable */
// This file is auto-generated by scripts/generate-rules.ts
// Do not edit this file directly.

export const REACT_PERF_RULE_NAMES = [
  'jsx-no-jsx-as-prop',
  'jsx-no-new-array-as-prop',
  'jsx-no-new-function-as-prop',
  'jsx-no-new-object-as-prop',
] as const

export type ReactPerfRuleName = (typeof REACT_PERF_RULE_NAMES)[number]

export interface ReactPerfRuleOptionsByName {
  'react-perf/jsx-no-jsx-as-prop': never
  'react-perf/jsx-no-new-array-as-prop': never
  'react-perf/jsx-no-new-function-as-prop': never
  'react-perf/jsx-no-new-object-as-prop': never
}
