/* oxlint-disable */
// This file is auto-generated by scripts/generate-rules.ts
// Do not edit this file directly.

export const REACT_RULE_NAMES = [
  'button-has-type',
  'checked-requires-onchange-or-readonly',
  'display-name',
  'exhaustive-deps',
  'forbid-component-props',
  'forbid-dom-props',
  'forbid-elements',
  'forward-ref-uses-ref',
  'hook-use-state',
  'iframe-missing-sandbox',
  'jsx-boolean-value',
  'jsx-curly-brace-presence',
  'jsx-filename-extension',
  'jsx-fragments',
  'jsx-handler-names',
  'jsx-key',
  'jsx-max-depth',
  'jsx-no-comment-textnodes',
  'jsx-no-constructed-context-values',
  'jsx-no-duplicate-props',
  'jsx-no-script-url',
  'jsx-no-target-blank',
  'jsx-no-undef',
  'jsx-no-useless-fragment',
  'jsx-pascal-case',
  'jsx-props-no-spread-multi',
  'jsx-props-no-spreading',
  'no-array-index-key',
  'no-children-prop',
  'no-clone-element',
  'no-danger',
  'no-danger-with-children',
  'no-did-mount-set-state',
  'no-did-update-set-state',
  'no-direct-mutation-state',
  'no-find-dom-node',
  'no-is-mounted',
  'no-multi-comp',
  'no-namespace',
  'no-react-children',
  'no-redundant-should-component-update',
  'no-render-return-value',
  'no-set-state',
  'no-string-refs',
  'no-this-in-sfc',
  'no-unescaped-entities',
  'no-unknown-property',
  'no-unsafe',
  'no-will-update-set-state',
  'only-export-components',
  'prefer-es6-class',
  'prefer-function-component',
  'react-in-jsx-scope',
  'require-render-return',
  'rules-of-hooks',
  'self-closing-comp',
  'state-in-constructor',
  'style-prop-object',
  'void-dom-elements-no-children',
] as const

export type ReactRuleName = (typeof REACT_RULE_NAMES)[number]

export interface ReactRuleOptionsByName {
  'react/button-has-type': {
    button?: boolean
    submit?: boolean
    reset?: boolean
  }
  'react/checked-requires-onchange-or-readonly': {
    ignoreMissingProperties?: boolean
    ignoreExclusiveCheckedAttribute?: boolean
  }
  'react/display-name': {
    ignoreTranspilerName?: boolean
    checkContextObjects?: boolean
  }
  'react/exhaustive-deps': {
    additionalHooks?: string
  }
  'react/forbid-component-props': {
    forbid?: readonly unknown[]
  }
  'react/forbid-dom-props': {
    forbid?: readonly unknown[]
  }
  'react/forbid-elements': {
    forbid?: readonly unknown[]
  }
  'react/forward-ref-uses-ref': never
  'react/hook-use-state': {
    allowDestructuredState?: boolean
  }
  'react/iframe-missing-sandbox': never
  'react/jsx-boolean-value': readonly [
    'always' | 'never',
    {
      always?: unknown
      never?: unknown
      assumeUndefinedIsFalse?: boolean
    },
  ]
  'react/jsx-curly-brace-presence': {
    props?: 'always' | 'never' | 'ignore'
    children?: 'always' | 'never' | 'ignore'
    propElementValues?: 'always' | 'never' | 'ignore'
  }
  'react/jsx-filename-extension': {
    allow?: 'always' | 'as-needed'
    extensions?: readonly string[]
    ignoreFilesWithoutCode?: boolean
  }
  'react/jsx-fragments': 'syntax' | 'element'
  'react/jsx-handler-names': {
    checkInlineFunctions?: boolean
    checkLocalVariables?: boolean
    eventHandlerPropPrefixes?: string
    eventHandlerPrefixes?: string
    ignoreComponentNames?: readonly string[]
    eventHandlerRegex?: string
    eventHandlerPropRegex?: string
  }
  'react/jsx-key': {
    checkKeyMustBeforeSpread?: boolean
    warnOnDuplicates?: boolean
    checkFragmentShorthand?: boolean
  }
  'react/jsx-max-depth': {
    max?: number
  }
  'react/jsx-no-comment-textnodes': never
  'react/jsx-no-constructed-context-values': never
  'react/jsx-no-duplicate-props': never
  'react/jsx-no-script-url': {
    includeFromSettings?: boolean
    components?: unknown
  }
  'react/jsx-no-target-blank': {
    enforceDynamicLinks?: 'always' | 'never'
    warnOnSpreadAttributes?: boolean
    allowReferrer?: boolean
    links?: boolean
    forms?: boolean
  }
  'react/jsx-no-undef': never
  'react/jsx-no-useless-fragment': {
    allowExpressions?: boolean
  }
  'react/jsx-pascal-case': {
    allowAllCaps?: boolean
    allowNamespace?: boolean
    allowLeadingUnderscore?: boolean
    ignore?: readonly string[]
  }
  'react/jsx-props-no-spread-multi': never
  'react/jsx-props-no-spreading': {
    html?: 'ignore' | 'enforce'
    custom?: 'ignore' | 'enforce'
    explicitSpread?: 'ignore' | 'enforce'
    exceptions?: readonly string[]
  }
  'react/no-array-index-key': never
  'react/no-children-prop': never
  'react/no-clone-element': never
  'react/no-danger': never
  'react/no-danger-with-children': never
  'react/no-did-mount-set-state': 'allowed' | 'disallow-in-func'
  'react/no-did-update-set-state': 'allowed' | 'disallow-in-func'
  'react/no-direct-mutation-state': never
  'react/no-find-dom-node': never
  'react/no-is-mounted': never
  'react/no-multi-comp': {
    ignoreStateless?: boolean
  }
  'react/no-namespace': never
  'react/no-react-children': never
  'react/no-redundant-should-component-update': never
  'react/no-render-return-value': never
  'react/no-set-state': never
  'react/no-string-refs': {
    noTemplateLiterals?: boolean
  }
  'react/no-this-in-sfc': never
  'react/no-unescaped-entities': never
  'react/no-unknown-property': {
    ignore?: unknown
  }
  'react/no-unsafe': {
    checkAliases?: boolean
  }
  'react/no-will-update-set-state': 'allowed' | 'disallow-in-func'
  'react/only-export-components': {
    allowExportNames?: unknown
    allowConstantExport?: boolean
    customHOCs?: readonly string[]
    checkJS?: boolean
  }
  'react/prefer-es6-class': 'always' | 'never'
  'react/prefer-function-component': {
    allowErrorBoundary?: boolean
    allowJsxUtilityClass?: boolean
  }
  'react/react-in-jsx-scope': never
  'react/require-render-return': never
  'react/rules-of-hooks': never
  'react/self-closing-comp': {
    component?: boolean
    html?: boolean
  }
  'react/state-in-constructor': 'always' | 'never'
  'react/style-prop-object': {
    allow?: readonly string[]
  }
  'react/void-dom-elements-no-children': never
}
