/* oxlint-disable */
// This file is auto-generated by scripts/generate-rules.ts
// Do not edit this file directly.

export const TYPESCRIPT_RULE_NAMES = [
  'adjacent-overload-signatures',
  'array-type',
  'await-thenable',
  'ban-ts-comment',
  'ban-tslint-comment',
  'ban-types',
  'class-literal-property-style',
  'consistent-generic-constructors',
  'consistent-indexed-object-style',
  'consistent-return',
  'consistent-type-assertions',
  'consistent-type-definitions',
  'consistent-type-exports',
  'consistent-type-imports',
  'dot-notation',
  'explicit-function-return-type',
  'explicit-member-accessibility',
  'explicit-module-boundary-types',
  'no-array-delete',
  'no-base-to-string',
  'no-confusing-non-null-assertion',
  'no-confusing-void-expression',
  'no-deprecated',
  'no-duplicate-enum-values',
  'no-duplicate-type-constituents',
  'no-dynamic-delete',
  'no-empty-interface',
  'no-empty-object-type',
  'no-explicit-any',
  'no-extra-non-null-assertion',
  'no-extraneous-class',
  'no-floating-promises',
  'no-for-in-array',
  'no-implied-eval',
  'no-import-type-side-effects',
  'no-inferrable-types',
  'no-invalid-void-type',
  'no-meaningless-void-operator',
  'no-misused-new',
  'no-misused-promises',
  'no-misused-spread',
  'no-mixed-enums',
  'no-namespace',
  'no-non-null-asserted-nullish-coalescing',
  'no-non-null-asserted-optional-chain',
  'no-non-null-assertion',
  'no-redundant-type-constituents',
  'no-require-imports',
  'no-restricted-types',
  'no-this-alias',
  'no-unnecessary-boolean-literal-compare',
  'no-unnecessary-condition',
  'no-unnecessary-parameter-property-assignment',
  'no-unnecessary-qualifier',
  'no-unnecessary-template-expression',
  'no-unnecessary-type-arguments',
  'no-unnecessary-type-assertion',
  'no-unnecessary-type-constraint',
  'no-unnecessary-type-conversion',
  'no-unnecessary-type-parameters',
  'no-unsafe-argument',
  'no-unsafe-assignment',
  'no-unsafe-call',
  'no-unsafe-declaration-merging',
  'no-unsafe-enum-comparison',
  'no-unsafe-function-type',
  'no-unsafe-member-access',
  'no-unsafe-return',
  'no-unsafe-type-assertion',
  'no-unsafe-unary-minus',
  'no-useless-default-assignment',
  'no-useless-empty-export',
  'no-var-requires',
  'no-wrapper-object-types',
  'non-nullable-type-assertion-style',
  'only-throw-error',
  'parameter-properties',
  'prefer-as-const',
  'prefer-enum-initializers',
  'prefer-find',
  'prefer-for-of',
  'prefer-function-type',
  'prefer-includes',
  'prefer-literal-enum-member',
  'prefer-namespace-keyword',
  'prefer-nullish-coalescing',
  'prefer-optional-chain',
  'prefer-promise-reject-errors',
  'prefer-readonly',
  'prefer-readonly-parameter-types',
  'prefer-reduce-type-parameter',
  'prefer-regexp-exec',
  'prefer-return-this-type',
  'prefer-string-starts-ends-with',
  'prefer-ts-expect-error',
  'promise-function-async',
  'related-getter-setter-pairs',
  'require-array-sort-compare',
  'require-await',
  'restrict-plus-operands',
  'restrict-template-expressions',
  'return-await',
  'strict-boolean-expressions',
  'strict-void-return',
  'switch-exhaustiveness-check',
  'triple-slash-reference',
  'unbound-method',
  'unified-signatures',
  'use-unknown-in-catch-callback-variable',
] as const

export type TypescriptRuleName = (typeof TYPESCRIPT_RULE_NAMES)[number]

export interface TypescriptRuleOptionsByName {
  'typescript/adjacent-overload-signatures': never
  'typescript/array-type': {
    default?: 'array' | 'array-simple' | 'generic'
    readonly?: 'array' | 'array-simple' | 'generic'
  }
  'typescript/await-thenable': never
  'typescript/ban-ts-comment': {
    ts_expect_error?: 'allow-with-description'
    ts_ignore?: 'allow-with-description'
    ts_nocheck?: 'allow-with-description'
    ts_check?: 'allow-with-description'
    minimumDescriptionLength?: number
  }
  'typescript/ban-tslint-comment': never
  'typescript/ban-types': never
  'typescript/class-literal-property-style': 'Fields' | 'Getters'
  'typescript/consistent-generic-constructors': {
    option?: 'constructor' | 'type-annotation'
  }
  'typescript/consistent-indexed-object-style': 'record' | 'index-signature'
  'typescript/consistent-return': {
    treatUndefinedAsUnspecified?: boolean
  }
  'typescript/consistent-type-assertions': {
    assertionStyle?: 'as' | 'angle-bracket' | 'never'
    objectLiteralTypeAssertions?: 'allow' | 'allow-as-parameter' | 'never'
    arrayLiteralTypeAssertions?: 'allow' | 'allow-as-parameter' | 'never'
  }
  'typescript/consistent-type-definitions': 'interface' | 'type'
  'typescript/consistent-type-exports': {
    fixMixedExportsWithInlineTypeSpecifier?: boolean
  }
  'typescript/consistent-type-imports': {
    disallowTypeAnnotations?: boolean
    fixStyle?: 'separate-type-imports' | 'inline-type-imports'
    prefer?: 'type-imports' | 'no-type-imports'
  }
  'typescript/dot-notation': {
    allowIndexSignaturePropertyAccess?: boolean
    allowKeywords?: boolean
    allowPattern?: string
    allowPrivateClassPropertyAccess?: boolean
    allowProtectedClassPropertyAccess?: boolean
  }
  'typescript/explicit-function-return-type': {
    allowExpressions?: boolean
    allowTypedFunctionExpressions?: boolean
    allowDirectConstAssertionInArrowFunctions?: boolean
    allowConciseArrowFunctionExpressionsStartingWithVoid?: boolean
    allowFunctionsWithoutTypeParameters?: boolean
    allowedNames?: unknown
    allowHigherOrderFunctions?: boolean
    allowIIFEs?: boolean
  }
  'typescript/explicit-member-accessibility': {
    accessibility?: 'explicit' | 'no-public' | 'off'
    overrides?: {
      accessors?: 'explicit' | 'no-public' | 'off'
      constructors?: 'explicit' | 'no-public' | 'off'
      methods?: 'explicit' | 'no-public' | 'off'
      parameterProperties?: 'explicit' | 'no-public' | 'off'
      properties?: 'explicit' | 'no-public' | 'off'
    }
    ignoredMethodNames?: readonly string[]
  }
  'typescript/explicit-module-boundary-types': {
    allowArgumentsExplicitlyTypedAsAny?: boolean
    allowDirectConstAssertionInArrowFunctions?: boolean
    allowedNames?: readonly string[]
    allowHigherOrderFunctions?: boolean
    allowOverloadFunctions?: boolean
    allowTypedFunctionExpressions?: boolean
  }
  'typescript/no-array-delete': never
  'typescript/no-base-to-string': {
    checkUnknown?: boolean
    ignoredTypeNames?: readonly string[]
  }
  'typescript/no-confusing-non-null-assertion': never
  'typescript/no-confusing-void-expression': {
    ignoreArrowShorthand?: boolean
    ignoreVoidOperator?: boolean
    ignoreVoidReturningFunctions?: boolean
  }
  'typescript/no-deprecated': {
    allow?: readonly unknown[]
  }
  'typescript/no-duplicate-enum-values': never
  'typescript/no-duplicate-type-constituents': {
    ignoreIntersections?: boolean
    ignoreUnions?: boolean
  }
  'typescript/no-dynamic-delete': never
  'typescript/no-empty-interface': never
  'typescript/no-empty-object-type': {
    allowInterfaces?: 'never' | 'always' | 'with-single-extends'
    allowObjectTypes?: 'never' | 'always'
    allowWithName?: string
  }
  'typescript/no-explicit-any': {
    fixToUnknown?: boolean
    ignoreRestArgs?: boolean
  }
  'typescript/no-extra-non-null-assertion': never
  'typescript/no-extraneous-class': {
    allowConstructorOnly?: boolean
    allowEmpty?: boolean
    allowStaticOnly?: boolean
    allowWithDecorator?: boolean
  }
  'typescript/no-floating-promises': {
    allowForKnownSafeCalls?: readonly unknown[]
    allowForKnownSafePromises?: readonly unknown[]
    checkThenables?: boolean
    ignoreIIFE?: boolean
    ignoreVoid?: boolean
  }
  'typescript/no-for-in-array': never
  'typescript/no-implied-eval': never
  'typescript/no-import-type-side-effects': never
  'typescript/no-inferrable-types': {
    ignoreParameters?: boolean
    ignoreProperties?: boolean
  }
  'typescript/no-invalid-void-type': {
    allowAsThisParameter?: boolean
    allowInGenericTypeArguments?: unknown
  }
  'typescript/no-meaningless-void-operator': {
    checkNever?: boolean
  }
  'typescript/no-misused-new': never
  'typescript/no-misused-promises': {
    checksConditionals?: boolean
    checksSpreads?: boolean
    checksVoidReturn?: unknown
  }
  'typescript/no-misused-spread': {
    allow?: readonly unknown[]
  }
  'typescript/no-mixed-enums': never
  'typescript/no-namespace': {
    allowDeclarations?: boolean
    allowDefinitionFiles?: boolean
  }
  'typescript/no-non-null-asserted-nullish-coalescing': never
  'typescript/no-non-null-asserted-optional-chain': never
  'typescript/no-non-null-assertion': never
  'typescript/no-redundant-type-constituents': never
  'typescript/no-require-imports': {
    allow?: readonly string[]
    allowAsImport?: boolean
  }
  'typescript/no-restricted-types': {
    types?: unknown
  }
  'typescript/no-this-alias': {
    allowDestructuring?: boolean
  }
  'typescript/no-unnecessary-boolean-literal-compare': {
    allowComparingNullableBooleansToFalse?: boolean
    allowComparingNullableBooleansToTrue?: boolean
  }
  'typescript/no-unnecessary-condition': {
    allowConstantLoopConditions?: unknown
    checkTypePredicates?: boolean
  }
  'typescript/no-unnecessary-parameter-property-assignment': never
  'typescript/no-unnecessary-qualifier': never
  'typescript/no-unnecessary-template-expression': never
  'typescript/no-unnecessary-type-arguments': never
  'typescript/no-unnecessary-type-assertion': {
    checkLiteralConstAssertions?: boolean
    typesToIgnore?: readonly string[]
  }
  'typescript/no-unnecessary-type-constraint': never
  'typescript/no-unnecessary-type-conversion': never
  'typescript/no-unnecessary-type-parameters': never
  'typescript/no-unsafe-argument': never
  'typescript/no-unsafe-assignment': never
  'typescript/no-unsafe-call': never
  'typescript/no-unsafe-declaration-merging': never
  'typescript/no-unsafe-enum-comparison': never
  'typescript/no-unsafe-function-type': never
  'typescript/no-unsafe-member-access': {
    allowOptionalChaining?: boolean
  }
  'typescript/no-unsafe-return': never
  'typescript/no-unsafe-type-assertion': never
  'typescript/no-unsafe-unary-minus': never
  'typescript/no-useless-default-assignment': never
  'typescript/no-useless-empty-export': never
  'typescript/no-var-requires': never
  'typescript/no-wrapper-object-types': never
  'typescript/non-nullable-type-assertion-style': never
  'typescript/only-throw-error': {
    allow?: readonly unknown[]
    allowRethrowing?: boolean
    allowThrowingAny?: boolean
    allowThrowingUnknown?: boolean
  }
  'typescript/parameter-properties': {
    allow?: readonly (
      | 'private'
      | 'private readonly'
      | 'protected'
      | 'protected readonly'
      | 'public'
      | 'public readonly'
      | 'readonly'
    )[]
    prefer?: 'class-property' | 'parameter-property'
  }
  'typescript/prefer-as-const': never
  'typescript/prefer-enum-initializers': never
  'typescript/prefer-find': never
  'typescript/prefer-for-of': never
  'typescript/prefer-function-type': never
  'typescript/prefer-includes': never
  'typescript/prefer-literal-enum-member': {
    allowBitwiseExpressions?: boolean
  }
  'typescript/prefer-namespace-keyword': never
  'typescript/prefer-nullish-coalescing': {
    ignoreBooleanCoercion?: boolean
    ignoreConditionalTests?: boolean
    ignoreIfStatements?: boolean
    ignoreMixedLogicalExpressions?: boolean
    ignoreTernaryTests?: boolean
    ignorePrimitives?: unknown
  }
  'typescript/prefer-optional-chain': {
    allowPotentiallyUnsafeFixesThatModifyTheReturnTypeIKnowWhatImDoing?: boolean
    checkAny?: boolean
    checkBigInt?: boolean
    checkBoolean?: boolean
    checkNumber?: boolean
    checkString?: boolean
    checkUnknown?: boolean
    requireNullish?: boolean
  }
  'typescript/prefer-promise-reject-errors': {
    allow?: readonly unknown[]
    allowEmptyReject?: boolean
    allowThrowingAny?: boolean
    allowThrowingUnknown?: boolean
  }
  'typescript/prefer-readonly': {
    onlyInlineLambdas?: boolean
  }
  'typescript/prefer-readonly-parameter-types': {
    allow?: readonly unknown[]
    checkParameterProperties?: boolean
    ignoreInferredTypes?: boolean
    treatMethodsAsReadonly?: boolean
  }
  'typescript/prefer-reduce-type-parameter': never
  'typescript/prefer-regexp-exec': never
  'typescript/prefer-return-this-type': never
  'typescript/prefer-string-starts-ends-with': {
    allowSingleElementEquality?: 'always' | 'never'
  }
  'typescript/prefer-ts-expect-error': never
  'typescript/promise-function-async': {
    allowAny?: boolean
    allowedPromiseNames?: readonly string[]
    checkArrowFunctions?: boolean
    checkFunctionDeclarations?: boolean
    checkFunctionExpressions?: boolean
    checkMethodDeclarations?: boolean
  }
  'typescript/related-getter-setter-pairs': never
  'typescript/require-array-sort-compare': {
    ignoreStringArrays?: boolean
  }
  'typescript/require-await': never
  'typescript/restrict-plus-operands': {
    allowAny?: boolean
    allowBoolean?: boolean
    allowNullish?: boolean
    allowNumberAndString?: boolean
    allowRegExp?: boolean
    skipCompoundAssignments?: boolean
  }
  'typescript/restrict-template-expressions': {
    allowAny?: boolean
    allowArray?: boolean
    allowBoolean?: boolean
    allowNullish?: boolean
    allowNumber?: boolean
    allowRegExp?: boolean
    allowNever?: boolean
    allow?: readonly unknown[]
  }
  'typescript/return-await':
    | 'in-try-catch'
    | 'always'
    | 'error-handling-correctness-only'
    | 'never'
  'typescript/strict-boolean-expressions': {
    allowAny?: boolean
    allowNullableBoolean?: boolean
    allowNullableNumber?: boolean
    allowNullableString?: boolean
    allowNullableEnum?: boolean
    allowNullableObject?: boolean
    allowString?: boolean
    allowNumber?: boolean
  }
  'typescript/strict-void-return': {
    allowReturnAny?: boolean
  }
  'typescript/switch-exhaustiveness-check': {
    allowDefaultCaseForExhaustiveSwitch?: boolean
    considerDefaultExhaustiveForUnions?: boolean
    defaultCaseCommentPattern?: string
    requireDefaultForNonUnion?: boolean
  }
  'typescript/triple-slash-reference': {
    lib?: 'always' | 'never'
    path?: 'always' | 'never'
    types?: 'always' | 'never' | 'prefer-import'
  }
  'typescript/unbound-method': {
    ignoreStatic?: boolean
  }
  'typescript/unified-signatures': {
    ignoreDifferentlyNamedParameters?: boolean
    ignoreOverloadsWithDifferentJSDoc?: boolean
  }
  'typescript/use-unknown-in-catch-callback-variable': never
}
