/* oxlint-disable */
// This file is auto-generated by scripts/generate-rules.ts
// Do not edit this file directly.

export const UNICORN_RULE_NAMES = [
  'catch-error-name',
  'consistent-assert',
  'consistent-date-clone',
  'consistent-empty-array-spread',
  'consistent-existence-index-check',
  'consistent-function-scoping',
  'consistent-template-literal-escape',
  'custom-error-definition',
  'empty-brace-spaces',
  'error-message',
  'escape-case',
  'explicit-length-check',
  'filename-case',
  'import-style',
  'new-for-builtins',
  'no-abusive-eslint-disable',
  'no-accessor-recursion',
  'no-anonymous-default-export',
  'no-array-callback-reference',
  'no-array-for-each',
  'no-array-method-this-argument',
  'no-array-reduce',
  'no-array-reverse',
  'no-array-sort',
  'no-await-expression-member',
  'no-await-in-promise-methods',
  'no-console-spaces',
  'no-document-cookie',
  'no-empty-file',
  'no-hex-escape',
  'no-immediate-mutation',
  'no-instanceof-array',
  'no-instanceof-builtins',
  'no-invalid-fetch-options',
  'no-invalid-remove-event-listener',
  'no-length-as-slice-end',
  'no-lonely-if',
  'no-magic-array-flat-depth',
  'no-negated-condition',
  'no-negation-in-equality-check',
  'no-nested-ternary',
  'no-new-array',
  'no-new-buffer',
  'no-null',
  'no-object-as-default-parameter',
  'no-process-exit',
  'no-single-promise-in-promise-methods',
  'no-static-only-class',
  'no-thenable',
  'no-this-assignment',
  'no-typeof-undefined',
  'no-unnecessary-array-flat-depth',
  'no-unnecessary-array-splice-count',
  'no-unnecessary-await',
  'no-unnecessary-slice-end',
  'no-unreadable-array-destructuring',
  'no-unreadable-iife',
  'no-useless-collection-argument',
  'no-useless-error-capture-stack-trace',
  'no-useless-fallback-in-spread',
  'no-useless-iterator-to-array',
  'no-useless-length-check',
  'no-useless-promise-resolve-reject',
  'no-useless-spread',
  'no-useless-switch-case',
  'no-useless-undefined',
  'no-zero-fractions',
  'number-literal-case',
  'numeric-separators-style',
  'prefer-add-event-listener',
  'prefer-array-find',
  'prefer-array-flat',
  'prefer-array-flat-map',
  'prefer-array-index-of',
  'prefer-array-some',
  'prefer-at',
  'prefer-bigint-literals',
  'prefer-blob-reading-methods',
  'prefer-class-fields',
  'prefer-classlist-toggle',
  'prefer-code-point',
  'prefer-date-now',
  'prefer-default-parameters',
  'prefer-dom-node-append',
  'prefer-dom-node-dataset',
  'prefer-dom-node-remove',
  'prefer-dom-node-text-content',
  'prefer-event-target',
  'prefer-global-this',
  'prefer-import-meta-properties',
  'prefer-includes',
  'prefer-keyboard-event-key',
  'prefer-logical-operator-over-ternary',
  'prefer-math-min-max',
  'prefer-math-trunc',
  'prefer-modern-dom-apis',
  'prefer-modern-math-apis',
  'prefer-module',
  'prefer-native-coercion-functions',
  'prefer-negative-index',
  'prefer-node-protocol',
  'prefer-number-properties',
  'prefer-object-from-entries',
  'prefer-optional-catch-binding',
  'prefer-prototype-methods',
  'prefer-query-selector',
  'prefer-reflect-apply',
  'prefer-regexp-test',
  'prefer-response-static-json',
  'prefer-set-has',
  'prefer-set-size',
  'prefer-spread',
  'prefer-string-raw',
  'prefer-string-replace-all',
  'prefer-string-slice',
  'prefer-string-starts-ends-with',
  'prefer-string-trim-start-end',
  'prefer-structured-clone',
  'prefer-ternary',
  'prefer-top-level-await',
  'prefer-type-error',
  'relative-url-style',
  'require-array-join-separator',
  'require-module-attributes',
  'require-module-specifiers',
  'require-number-to-fixed-digits-argument',
  'require-post-message-target-origin',
  'switch-case-braces',
  'switch-case-break-position',
  'text-encoding-identifier-case',
  'throw-new-error',
] as const

export type UnicornRuleName = (typeof UNICORN_RULE_NAMES)[number]

export interface UnicornRuleOptionsByName {
  'unicorn/catch-error-name': {
    ignore?: readonly string[]
    name?: string
  }
  'unicorn/consistent-assert': never
  'unicorn/consistent-date-clone': never
  'unicorn/consistent-empty-array-spread': never
  'unicorn/consistent-existence-index-check': never
  'unicorn/consistent-function-scoping': {
    checkArrowFunctions?: boolean
  }
  'unicorn/consistent-template-literal-escape': never
  'unicorn/custom-error-definition': never
  'unicorn/empty-brace-spaces': never
  'unicorn/error-message': never
  'unicorn/escape-case': never
  'unicorn/explicit-length-check': {
    'non-zero'?: 'greater-than' | 'not-equal'
  }
  'unicorn/filename-case': {
    cases?: {
      kebabCase?: boolean
      camelCase?: boolean
      snakeCase?: boolean
      pascalCase?: boolean
    }
    case?: 'kebabCase' | 'camelCase' | 'snakeCase' | 'pascalCase'
    ignore?: string
    multipleFileExtensions?: boolean
  }
  'unicorn/import-style': unknown
  'unicorn/new-for-builtins': never
  'unicorn/no-abusive-eslint-disable': never
  'unicorn/no-accessor-recursion': never
  'unicorn/no-anonymous-default-export': never
  'unicorn/no-array-callback-reference': never
  'unicorn/no-array-for-each': never
  'unicorn/no-array-method-this-argument': never
  'unicorn/no-array-reduce': {
    allowSimpleOperations?: boolean
  }
  'unicorn/no-array-reverse': {
    allowExpressionStatement?: boolean
  }
  'unicorn/no-array-sort': {
    allowExpressionStatement?: boolean
  }
  'unicorn/no-await-expression-member': never
  'unicorn/no-await-in-promise-methods': never
  'unicorn/no-console-spaces': never
  'unicorn/no-document-cookie': never
  'unicorn/no-empty-file': never
  'unicorn/no-hex-escape': never
  'unicorn/no-immediate-mutation': never
  'unicorn/no-instanceof-array': never
  'unicorn/no-instanceof-builtins': {
    include?: readonly string[]
    exclude?: readonly string[]
    useErrorIsError?: boolean
    strategy?: 'strict' | 'loose'
  }
  'unicorn/no-invalid-fetch-options': never
  'unicorn/no-invalid-remove-event-listener': never
  'unicorn/no-length-as-slice-end': never
  'unicorn/no-lonely-if': never
  'unicorn/no-magic-array-flat-depth': never
  'unicorn/no-negated-condition': never
  'unicorn/no-negation-in-equality-check': never
  'unicorn/no-nested-ternary': never
  'unicorn/no-new-array': never
  'unicorn/no-new-buffer': never
  'unicorn/no-null': {
    checkStrictEquality?: boolean
  }
  'unicorn/no-object-as-default-parameter': never
  'unicorn/no-process-exit': never
  'unicorn/no-single-promise-in-promise-methods': never
  'unicorn/no-static-only-class': never
  'unicorn/no-thenable': never
  'unicorn/no-this-assignment': never
  'unicorn/no-typeof-undefined': {
    checkGlobalVariables?: boolean
  }
  'unicorn/no-unnecessary-array-flat-depth': never
  'unicorn/no-unnecessary-array-splice-count': never
  'unicorn/no-unnecessary-await': never
  'unicorn/no-unnecessary-slice-end': never
  'unicorn/no-unreadable-array-destructuring': never
  'unicorn/no-unreadable-iife': never
  'unicorn/no-useless-collection-argument': never
  'unicorn/no-useless-error-capture-stack-trace': never
  'unicorn/no-useless-fallback-in-spread': never
  'unicorn/no-useless-iterator-to-array': never
  'unicorn/no-useless-length-check': never
  'unicorn/no-useless-promise-resolve-reject': {
    allowReject?: boolean
  }
  'unicorn/no-useless-spread': never
  'unicorn/no-useless-switch-case': never
  'unicorn/no-useless-undefined': {
    checkArguments?: boolean
    checkArrowFunctionBody?: boolean
  }
  'unicorn/no-zero-fractions': never
  'unicorn/number-literal-case': never
  'unicorn/numeric-separators-style': {
    onlyIfContainsSeparator?: boolean
    hexadecimal?: {
      groupLength?: number
      minimumDigits?: number
    }
    binary?: {
      groupLength?: number
      minimumDigits?: number
    }
    octal?: {
      groupLength?: number
      minimumDigits?: number
    }
    number?: {
      groupLength?: number
      minimumDigits?: number
    }
  }
  'unicorn/prefer-add-event-listener': never
  'unicorn/prefer-array-find': never
  'unicorn/prefer-array-flat': never
  'unicorn/prefer-array-flat-map': never
  'unicorn/prefer-array-index-of': never
  'unicorn/prefer-array-some': never
  'unicorn/prefer-at': {
    checkAllIndexAccess?: boolean
    getLastElementFunctions?: readonly string[]
  }
  'unicorn/prefer-bigint-literals': never
  'unicorn/prefer-blob-reading-methods': never
  'unicorn/prefer-class-fields': never
  'unicorn/prefer-classlist-toggle': never
  'unicorn/prefer-code-point': never
  'unicorn/prefer-date-now': never
  'unicorn/prefer-default-parameters': never
  'unicorn/prefer-dom-node-append': never
  'unicorn/prefer-dom-node-dataset': never
  'unicorn/prefer-dom-node-remove': never
  'unicorn/prefer-dom-node-text-content': never
  'unicorn/prefer-event-target': never
  'unicorn/prefer-global-this': never
  'unicorn/prefer-import-meta-properties': never
  'unicorn/prefer-includes': never
  'unicorn/prefer-keyboard-event-key': never
  'unicorn/prefer-logical-operator-over-ternary': never
  'unicorn/prefer-math-min-max': never
  'unicorn/prefer-math-trunc': never
  'unicorn/prefer-modern-dom-apis': never
  'unicorn/prefer-modern-math-apis': never
  'unicorn/prefer-module': never
  'unicorn/prefer-native-coercion-functions': never
  'unicorn/prefer-negative-index': never
  'unicorn/prefer-node-protocol': never
  'unicorn/prefer-number-properties': {
    checkInfinity?: boolean
    checkNaN?: boolean
  }
  'unicorn/prefer-object-from-entries': {
    functions?: readonly string[]
  }
  'unicorn/prefer-optional-catch-binding': never
  'unicorn/prefer-prototype-methods': never
  'unicorn/prefer-query-selector': never
  'unicorn/prefer-reflect-apply': never
  'unicorn/prefer-regexp-test': never
  'unicorn/prefer-response-static-json': never
  'unicorn/prefer-set-has': never
  'unicorn/prefer-set-size': never
  'unicorn/prefer-spread': never
  'unicorn/prefer-string-raw': never
  'unicorn/prefer-string-replace-all': never
  'unicorn/prefer-string-slice': never
  'unicorn/prefer-string-starts-ends-with': never
  'unicorn/prefer-string-trim-start-end': never
  'unicorn/prefer-structured-clone': {
    functions?: readonly string[]
  }
  'unicorn/prefer-ternary': 'always' | 'only-single-line'
  'unicorn/prefer-top-level-await': never
  'unicorn/prefer-type-error': never
  'unicorn/relative-url-style': 'never' | 'always'
  'unicorn/require-array-join-separator': never
  'unicorn/require-module-attributes': never
  'unicorn/require-module-specifiers': never
  'unicorn/require-number-to-fixed-digits-argument': never
  'unicorn/require-post-message-target-origin': never
  'unicorn/switch-case-braces': 'always' | 'avoid'
  'unicorn/switch-case-break-position': never
  'unicorn/text-encoding-identifier-case': {
    withDash?: boolean
  }
  'unicorn/throw-new-error': never
}
