/* oxlint-disable */
// This file is auto-generated by scripts/generate-rules.ts
// Do not edit this file directly.

export const VITEST_RULE_NAMES = [
  'consistent-each-for',
  'consistent-test-filename',
  'consistent-test-it',
  'consistent-vitest-vi',
  'expect-expect',
  'hoisted-apis-on-top',
  'max-expects',
  'max-nested-describe',
  'no-alias-methods',
  'no-commented-out-tests',
  'no-conditional-expect',
  'no-conditional-in-test',
  'no-conditional-tests',
  'no-disabled-tests',
  'no-duplicate-hooks',
  'no-focused-tests',
  'no-hooks',
  'no-identical-title',
  'no-import-node-test',
  'no-importing-vitest-globals',
  'no-interpolation-in-snapshots',
  'no-large-snapshots',
  'no-mocks-import',
  'no-restricted-matchers',
  'no-restricted-vi-methods',
  'no-standalone-expect',
  'no-test-prefixes',
  'no-test-return-statement',
  'no-unneeded-async-expect-function',
  'padding-around-after-all-blocks',
  'prefer-called-exactly-once-with',
  'prefer-called-once',
  'prefer-called-times',
  'prefer-called-with',
  'prefer-comparison-matcher',
  'prefer-describe-function-title',
  'prefer-each',
  'prefer-equality-matcher',
  'prefer-expect-assertions',
  'prefer-expect-resolves',
  'prefer-expect-type-of',
  'prefer-hooks-in-order',
  'prefer-hooks-on-top',
  'prefer-import-in-mock',
  'prefer-importing-vitest-globals',
  'prefer-lowercase-title',
  'prefer-mock-promise-shorthand',
  'prefer-mock-return-shorthand',
  'prefer-snapshot-hint',
  'prefer-spy-on',
  'prefer-strict-boolean-matchers',
  'prefer-strict-equal',
  'prefer-to-be',
  'prefer-to-be-falsy',
  'prefer-to-be-object',
  'prefer-to-be-truthy',
  'prefer-to-contain',
  'prefer-to-have-been-called-times',
  'prefer-to-have-length',
  'prefer-todo',
  'require-awaited-expect-poll',
  'require-hook',
  'require-local-test-context-for-concurrent-snapshots',
  'require-mock-type-parameters',
  'require-test-timeout',
  'require-to-throw-message',
  'require-top-level-describe',
  'valid-describe-callback',
  'valid-expect',
  'valid-expect-in-promise',
  'valid-title',
  'warn-todo',
] as const

export type VitestRuleName = (typeof VITEST_RULE_NAMES)[number]

export interface VitestRuleOptionsByName {
  'vitest/consistent-each-for': {
    describe?: 'For' | 'Each'
    suite?: 'For' | 'Each'
    test?: 'For' | 'Each'
    it?: 'For' | 'Each'
  }
  'vitest/consistent-test-filename': {
    allTestPattern?: unknown
    pattern?: unknown
  }
  'vitest/consistent-test-it': unknown
  'vitest/consistent-vitest-vi': {
    fn?: 'Vi' | 'Vitest'
  }
  'vitest/expect-expect': unknown
  'vitest/hoisted-apis-on-top': never
  'vitest/max-expects': unknown
  'vitest/max-nested-describe': unknown
  'vitest/no-alias-methods': never
  'vitest/no-commented-out-tests': never
  'vitest/no-conditional-expect': never
  'vitest/no-conditional-in-test': never
  'vitest/no-conditional-tests': never
  'vitest/no-disabled-tests': never
  'vitest/no-duplicate-hooks': never
  'vitest/no-focused-tests': never
  'vitest/no-hooks': unknown
  'vitest/no-identical-title': never
  'vitest/no-import-node-test': never
  'vitest/no-importing-vitest-globals': never
  'vitest/no-interpolation-in-snapshots': never
  'vitest/no-large-snapshots': unknown
  'vitest/no-mocks-import': never
  'vitest/no-restricted-matchers': unknown
  'vitest/no-restricted-vi-methods': unknown
  'vitest/no-standalone-expect': unknown
  'vitest/no-test-prefixes': never
  'vitest/no-test-return-statement': never
  'vitest/no-unneeded-async-expect-function': never
  'vitest/padding-around-after-all-blocks': unknown
  'vitest/prefer-called-exactly-once-with': never
  'vitest/prefer-called-once': never
  'vitest/prefer-called-times': never
  'vitest/prefer-called-with': never
  'vitest/prefer-comparison-matcher': never
  'vitest/prefer-describe-function-title': never
  'vitest/prefer-each': never
  'vitest/prefer-equality-matcher': never
  'vitest/prefer-expect-assertions': unknown
  'vitest/prefer-expect-resolves': never
  'vitest/prefer-expect-type-of': never
  'vitest/prefer-hooks-in-order': never
  'vitest/prefer-hooks-on-top': never
  'vitest/prefer-import-in-mock': {
    fixable?: boolean
  }
  'vitest/prefer-importing-vitest-globals': never
  'vitest/prefer-lowercase-title': unknown
  'vitest/prefer-mock-promise-shorthand': never
  'vitest/prefer-mock-return-shorthand': never
  'vitest/prefer-snapshot-hint': unknown
  'vitest/prefer-spy-on': never
  'vitest/prefer-strict-boolean-matchers': never
  'vitest/prefer-strict-equal': never
  'vitest/prefer-to-be': never
  'vitest/prefer-to-be-falsy': never
  'vitest/prefer-to-be-object': never
  'vitest/prefer-to-be-truthy': never
  'vitest/prefer-to-contain': never
  'vitest/prefer-to-have-been-called-times': never
  'vitest/prefer-to-have-length': never
  'vitest/prefer-todo': never
  'vitest/require-awaited-expect-poll': never
  'vitest/require-hook': unknown
  'vitest/require-local-test-context-for-concurrent-snapshots': never
  'vitest/require-mock-type-parameters': {
    checkImportFunctions?: boolean
  }
  'vitest/require-test-timeout': never
  'vitest/require-to-throw-message': never
  'vitest/require-top-level-describe': unknown
  'vitest/valid-describe-callback': never
  'vitest/valid-expect': unknown
  'vitest/valid-expect-in-promise': never
  'vitest/valid-title': unknown
  'vitest/warn-todo': never
}
