/* oxlint-disable */
// This file is auto-generated by scripts/generate-rules.ts
// Do not edit this file directly.

export const VUE_RULE_NAMES = [
  'define-emits-declaration',
  'define-props-declaration',
  'define-props-destructuring',
  'max-props',
  'no-arrow-functions-in-watch',
  'no-deprecated-data-object-declaration',
  'no-deprecated-delete-set',
  'no-deprecated-destroyed-lifecycle',
  'no-deprecated-events-api',
  'no-deprecated-model-definition',
  'no-deprecated-vue-config-keycodes',
  'no-export-in-script-setup',
  'no-import-compiler-macros',
  'no-lifecycle-after-await',
  'no-multiple-slot-args',
  'no-required-prop-with-default',
  'no-this-in-before-route-enter',
  'prefer-import-from-vue',
  'require-default-export',
  'require-typed-ref',
  'return-in-computed-property',
  'valid-define-emits',
  'valid-define-props',
] as const

export type VueRuleName = (typeof VUE_RULE_NAMES)[number]

export interface VueRuleOptionsByName {
  'vue/define-emits-declaration': 'type-based' | 'type-literal' | 'runtime'
  'vue/define-props-declaration': 'type-based' | 'runtime'
  'vue/define-props-destructuring': {
    destructure?: 'always' | 'never'
  }
  'vue/max-props': {
    maxProps?: number
  }
  'vue/no-arrow-functions-in-watch': never
  'vue/no-deprecated-data-object-declaration': never
  'vue/no-deprecated-delete-set': never
  'vue/no-deprecated-destroyed-lifecycle': never
  'vue/no-deprecated-events-api': never
  'vue/no-deprecated-model-definition': {
    allowVue3Compat?: boolean
  }
  'vue/no-deprecated-vue-config-keycodes': never
  'vue/no-export-in-script-setup': never
  'vue/no-import-compiler-macros': never
  'vue/no-lifecycle-after-await': never
  'vue/no-multiple-slot-args': never
  'vue/no-required-prop-with-default': never
  'vue/no-this-in-before-route-enter': never
  'vue/prefer-import-from-vue': never
  'vue/require-default-export': never
  'vue/require-typed-ref': never
  'vue/return-in-computed-property': {
    treatUndefinedAsUnspecified?: boolean
  }
  'vue/valid-define-emits': never
  'vue/valid-define-props': never
}
